### ISSUE TITLE
spaces/tab indentation in the sql editor

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#103]
It would be nice if there was a preference for the editors indent behaviour.
Also, while `<tab>`/`<shift + tab>` is commonly used to indent selections, `<cmd + [>` and `<cmd + ]>` are equally common and also work well if nothing is selected. Supporting both has probably no downsides.

Also: currently 4 spaces nearly (but not quite) equal the size of one `tab` character and so if I edit a query that I pasted from my source code (4 space indented) the lines indented in postico don't match the pre-indented lines.

**Comment by jakob** [comment]
I just released a minor bug fix version v1.0.2 which fixes the tab width problem.
See more [in the changelist](https://eggerapps.at/postico/docs/?file=changelist.html)

I'll tackle the other problems later since I'm currently working on some bigger changes to the editor.

**Comment by jakob** [comment]
I've now added preferences to change the number of spaces per tab, and you can now use spaces for indenting as well.
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1334.zip

(I'm not sure how well I implemented the spaces vs. tabs for indenting feature, since most apps I tried behave completely different in corner cases, but I think I came up with a reasonable bahavior)

**Comment by qwesda** [comment]
it look good to me so far. Will report if I encounter any issues
