### ISSUE TITLE
crashes while editing sql queries

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#108]
I currently get 2 or 3 crashes a day while editing sql queries/functions. I've been using the 1228/1230 builds of Postico. The crashes seem pretty random, I haven't been able to see any pattern yet.

a) are there any log/crash reports that I should collect to help you debug this?
b) while the windows/connections restore quite nicely, the content of the sql pane is gone when the program restarts. It would be nice if the data there would also persist. This is probably related to #18 / #106

**Comment by jakob** [comment]
There was a deadlock in the syntax highlighter that I fixed in build 1229. The issue resulted in a hang while editing queries.

If the issue continues with 1230 build, please email crash logs and samples to jakob@eggerapps.at

You can find logs in `~/Library/Logs/DiagnosticReports`

If the app is hanging (spinning beachball), you can create a sample of the process with activity monitor. Select Postico in activity monitor, click the info button, then click "Sample". 

I hope to implement #18 soon, which should also fix the problem of restoring the SQL query

**Comment by qwesda** [comment]
hmm, the `~/Library/Logs/DiagnosticReports` is empty except for `Postico_2015-10-07-215628_Daniels-MacBook-Air`. Maybe they aren't always written or they are deleted after are send to apple. I'll sample the process if I encounter the bug again. 

It is possible that I was only using the 1228 build and that you already caught the bug.

**Comment by jakob** [comment]
It really sounds like the issue I fixed in 1229.

There are probably no crash reports since Postico technically didn't crash; it just got stuck while two threads were waiting for another. OS X can't detect deadlocks, that's why you'd need to sample manually.

**Comment by qwesda** [comment]
makes sense

Daniel Schwarz <dan@butter.sh>
http://pgp.mit.edu/pks/lookup?op=get&search=0x1586760D7DBEDE3F

**Comment by jakob** [comment]
Fixed in version 1.0
https://eggerapps.at/postico/changelist.html
