### ISSUE TITLE
Paid version → App Store?

### ISSUE THREAD

**Issue by haihappen** [jakob/Postico#115]
Now that Postico is available in the App Store, how can someone transform the paid version into an App Store version. Is this even possible? Or do I have to rebuy the app in the MAS?

**Comment by jakob** [comment]
I've recently sent [an email](http://us6.campaign-archive1.com/?u=645ad6690d&id=1db5cadf92) about this to all Postico customers.

Unfortunately Apple doesn't offer a way to transfer existing licenses to the App Store. Theoretically I could use promo codes, but using promo codes in this manner would go against the developer agreement -- something I don't want to do.

The version from my website continues to be available, and at the moment most customers seem to prefer buying directly. (the price is slightly lower because Fastspring charges a lower commission than Apple)

However, I do understand that customers might prefer the Mac App Store version. In that case I can offer to refund your order, so you can buy it on the App Store without paying twice.
