### ISSUE TITLE
Ability to select and copy cells + extra pane to view longer texts. 

### ISSUE THREAD

**Issue by hwsoderlund** [jakob/Postico#132]
This is really two feature requests, but one depends on the other:  

1. Ability to select single or multiple cells, not just complete rows, and copy the values in the selected cells.  

2. In Navicat, which I sometimes use, there is a feature which allows you to select a single cell and then pop up a pane at the bottom of the application window where the full text is displayed, nicely formatted with text wrapping and line breaks. It is extremely convenient and saves you from having to copy the text and pasting it into a text editor just to view it. See the screen shot for how the feature works in Navicat.  

![navicat_example](https://cloud.githubusercontent.com/assets/3725915/11335132/15a14164-91da-11e5-8668-c8a1044e132b.png)

**Comment by jakob** [comment]
Regarding 1)
I'm not currently planning to switch to a grid-like interface. First of all that would be a lot of work, but more importantly, it would significantly change the way Postico works.

However, it is already possible to copy data from a single cells using the "Copy Cell" command from the context menu.


Regarding 2)
It's not necessary to implement cell selection to allow viewing long text. The table view in Postico has a side bar which allows viewing long text; this feature is still missing from the SQL query view and might be a solution for your issue.

An alternative would be to add some kind of button to cells with truncated contents, which would show a popover with the full text -- but I'm a bit sceptical, since this might make the interface very cluttered.

I'd also like to mention that Postico already has a way to view truncated text: you can hover your mouse over the cell, and you should see a tool tip with the full text appear.

**Comment by jakob** [comment]
PS: Thanks for taking the time to report this issue, and also for your suggestions and screenshots. I was aware that the SQL Query view has some usability quirks when working with long texts, but since I personally don't work with data like this, I really depend on customer feedback like yours to understand the full scope of the problem.

**Comment by hwsoderlund** [comment]
Thank you for your answers. I totally missed the tooltip, and the "copy cell" command in the context menu. That'll do me nicely for now. But you are right, the side bar in the table view would be an awesome addition to the sql query view. I assume it would have to be a read-only view in that case, which is fine. When browsing a table with lots of columns the side bar easily gets cluttered in the table view. In such situations it is nice to switch to the query view where I can specify only the columns I want. Having the side bar available in read-only mode would be really nice. 

How do you want me to handle this github issue? Close it and create a new feature request about including the table view sidebar in the sql query view?

**Comment by jakob** [comment]
Closing this issue and creating a new one for the sidebar would be perfect. Thanks!

**Comment by hwsoderlund** [comment]
Done
