### ISSUE TITLE
Advanced sorting in table view

### ISSUE THREAD

**Issue by bleonard33** [jakob/Postico#137]
It would be awesome to be able to sort by multiple columns in Table View so that once it finished sorting the main column, you can then sort by a secondary column all of the items that have the same value, and so on for multiple columns. (Less important, it would also be great to be able to sort by functions/custom SQL, most notably `random()`).

Ideally it would be a implementation of the Data Sorting window in pgAdmin:
![screen shot 2015-11-24 at 1 33 26 pm](https://cloud.githubusercontent.com/assets/8130234/11376735/5e3122f6-92b0-11e5-98bf-334d7c476bf7.png)

**Comment by jakob** [comment]
I've had this feature in mind for a long time already, but just haven't gotten around to implementing it yet. Sorting by expressions/functions would certainly be neat, but I'll start with columns first.

If you frequently need to randomly sample a specific table, a workaround could be to create a view that does `select * from some_table order by random()`. Since views in Postico are updateable, this could be a nice solution.

Anyway, I'm pretty busy right now, so I can't offer an ETA on this, but it's definitely a feature I want to implement in the future.

**Comment by jakob** [comment]
I added support for sorting by multiple columns in Postico build 9666.

You can download the latest build from [the changelog](https://releases.eggerapps.at/postico2/changelog?update_channel=1)
