### ISSUE TITLE
Issue 92 is not fixed - Geometries do not appear as EWKT

### ISSUE THREAD

**Issue by tblanchard** [jakob/Postico#140]
![unity-production unitydb public geographic_features 2015-12-03 13-35-28](https://cloud.githubusercontent.com/assets/166568/11574831/bc6d075e-99c2-11e5-9318-de3e56a0a286.jpg)

See image.

center is defined as geography(Point,4326)
boundary is defined as geography(Polygon,4326)

**Comment by jakob** [comment]
Thanks for letting me know. I wasn't aware that the geometry/geography types support options, so I just did a naive string comparison against the type name, which fails because of the expression in parenthesis.

Here's a build with a fix for this issue:
https://eggerapps-downloads.s3.amazonaws.com/postico-1283.zip

**Comment by tblanchard** [comment]
Much better.  Works as expected.
