### ISSUE TITLE
Fix Table & View sizes reported in Table List View

### ISSUE THREAD

**Issue by ear** [jakob/Postico#143]
Versions `PostgreSQL 9.4.5` and `Postico 0.28 (1211)`

Both the row count and the size information are zero.

![postico-mat-view-size-error](https://cloud.githubusercontent.com/assets/2104122/11657627/4a9217aa-9dbe-11e5-81d0-1e151a9caa2a.png)

**Comment by jakob** [comment]
Hmm. Postico probably uses a different method to estimate table size as psql. It looks like the size of the other table is also off.

Could you try using the ANALYZE command, and then refresh, to see if the sizes match? (if you right-click, you'll find the analyze command under "maintenance")

**Comment by ear** [comment]
I did `Maintenance > Analyze…` on the Materialized View, then refreshed, the results are:

Relation  | psql size | Postico size
------------ | ------------- | -------------
Table | 137 MB | 11.3 MB
Materialized View | 65 MB | 67.9 MB

OK I guess the materialized view is comparable enough. Any idea what is happening with the table? Analyzing that one and refreshing has no change.

**Comment by jakob** [comment]
Well, Postico just multiplies the number of pages used by the table (+ the toast table) with the default page size to get an estimate of the page size (see description of the field `relpages` here: http://www.postgresql.org/docs/9.4/static/catalog-pg-class.html)

I just checked what psql does, and it uses the `pg_table_size` function. The difference might be caused by two things:

1. Space used by visibility map & free space map might not be included in my estimate
2. According to the docs, relpages is only "an estimate used by the query planner".

I could fix this issue by using the `pg_table_size` function like psql does, but that may cause performance issues on big databases, since that function probably needs to access the disk for every table. `relpages` on the other hand is a cached value stored in the `pg_class` table and it should have no overhead.

I'll think about this. I either need to make it clear that the size is only an estimate, or I need to query the full size (but only when the list view is open).

**Comment by ear** [comment]
OK. Sounds good! Thank you.

**Comment by jakob** [comment]
A customer just brought another issue with table & view sizes to my attention: sizes are no longer updated when refreshing. I need to fix this, and when doing so I'll try to do it the same as psql for consistency.

**Comment by ear** [comment]
By the way yesterday over the 9.6.0 upgrade I was backing up my databases and realised I had a 3GB table "somewhere" that I forgot I left in a test database. I didn't have a favorite for it in Postico so I had to find where this space was held by other means.

The way I figured out where it was was with `psql -c "\l+"` . The reason I am mentioning this here is that the output of that command is quite similar to the `psql -c "\d+"` discussed here. As far as I can see there is currently no way to surface the overall shape and size of a cluster in Postico.

Do you think this information could fit somewhere? Reporting what is available together with what size the databases are could be useful. There may be issues of authentication that complicate matters though, I'm not sure 😃

**Comment by jakob** [comment]
I've decided not to fix this issue, and we've removed the view from Postico 2. Doing it properly would have been a lot of effort that I would prefer to spend on something else, and leaving the view in its semi-broken state wasn't ideal either.

Apologies to everyone who was using this view.
