### ISSUE TITLE
shp2pgsql for Postico 

### ISSUE THREAD

**Issue by dkuzhanov** [jakob/Postico#149]
Hi Jakob, 

I was wondering if there is a way to use shp2pgsql plugin in Postico?

Thanks,
DK

**Comment by jakob** [comment]
I'm not too familiar with PostGIS, but as far as I understand shp2pgsql is a command line tool for converting ESRI shapefiles into SQL commands. I'm not sure what kind of integration you are looking for?

There's no way to call shp2pgsql from Postico, but you can just execute the SQL generated by shp2pgsql in the SQL Query View. But since it's a command line tool, it's probably easier to just use psql instead of Postico.

I assume you are looking for an easy way to import GEO data into PostgreSQL; unfortunately there isn't one at the moment -- but I'd love to hear any suggestions you have for improving Postico.

**Comment by jakob** [comment]
Closing this issue since I didn't hear back. If you have any further questions, feel free to add comments or email me!
