### ISSUE TITLE
Where are settings stored?

### ISSUE THREAD

**Issue by nathanpalmer** [jakob/Postico#171]
I'd like to share my configuration between my Desktop and Laptop. I do this with several apps already by using BitTorrent Sync on specific directories. I didn't readily see something in Application Support. Curious if there was a folder where settings are stored (such as the databases I have saved) I can try this out on?

**Comment by jakob** [comment]
Favorites are stored in the Application Support folder in an SQLite db. Since Postico is sandboxed, you have to look inside the Containers folder in your library.

However, Postico assumes that nothing else modifies the favorites db while it is open. If you sync the file, make sure to quit Postico before making changes to it.

You can also just use the "export favorites" command to copy favorites to another Mac, but unfortunately that can't be automated.

**Comment by nathanpalmer** [comment]
Ok, thanks for the information. I attempted to symlink the directory to somewhere else but it couldn't be found when I opened up the app. I'll resort to the export/import flow for now.

**Comment by halo** [comment]
Just for clarification, this is the exact location. I copy-pasted the files from a time machine backup into this folder and all my favorites and the activated license showed up:

```bash
open ~/Library/Containers/at.eggerapps.Postico/Data/Library/Application\ Support/Postico
```
