### ISSUE TITLE
Add support for editing Indexes

### ISSUE THREAD

**Issue by petersirka** [jakob/Postico#19]
I have suggestion for adding the index settings.
Thanks.

**Comment by neverov** [comment]
I lack index support too, it would be great to manipulate indexes as well.
Thanks for the great work on the app!

**Comment by Otann** [comment]
I also vote for adding indexes.
Thanks for your amazing product.

**Comment by danillos** [comment]
+1 vote

**Comment by iamanders** [comment]
+1

**Comment by regabi** [comment]
+1

**Comment by tonyduan** [comment]
+1 -- thanks for working on this, @jakob!

**Comment by jakob** [comment]
I've just added some support for indexes. Postico now displays a list of indexes in the table structure view underneath the columns.

- you can edit the index name and add a comment
- you can delete indexes
- there is no GUI for creating new indexes yet
- there is no pretty graphical display of indexes yet, at the moment Postico just displays the index definition (SQL)

Despite the current limitations, I'm pretty sure that this feature will be very useful to many people.

You can download a prerelease here:
https://eggerapps-downloads.s3.amazonaws.com/postico-1240.zip

Let me know what you think.

**Comment by tonyduan** [comment]
This sounds great -- thanks for all your hard work, Jacob.

Jakob Egger wrote:

**Comment by regabi** [comment]
This is great Jakob, big upgrade!

**Comment by jakob** [comment]
I've just released version 1.0, which includes the features I've described above:
https://eggerapps.at/postico/changelist.html

I'm leaving this issue open to remind me to continue working on improved GUI tools for indexes (esp. creating new indexes)

**Comment by jakob** [comment]
Also, to give credit where credit is due: The new index feature was mostly programmed by my friend @wurmrobert. Robert is a bright software engineering student who started helping me with development recently. He'll probably work on the index creation GUI next.

**Comment by regabi** [comment]
Nicely done @wurmrobert!
Jakob, as promised, I'm buying the app now!

**Comment by seymores** [comment]
Creating new index is quite important.

**Comment by bezludny** [comment]
> Creating new index is quite important.

Same here.

**Comment by swrobel** [comment]
:+1: for adding/editing indexes

**Comment by johnmap** [comment]
+1 for creating indexes

**Comment by helloguille** [comment]
+1

**Comment by willtrking** [comment]
+1

**Comment by raspasov** [comment]
+1, please - btw your app is amazing, keep up the great work! : )

**Comment by CreepGin** [comment]
While GUI is important, creating an index manually is quite straightforward:

Go to the `SQL Query` view and execute something like:

```
CREATE INDEX user_createdat_index ON "User" USING btree ("createdAt")
```

**Comment by jakob** [comment]
It's been some time, but I've now finally finished the work that @wurmrobert started with the index editor: The graphical index editor is now ready for testing!

Please download the latest prerelease build here:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1560.zip

I'm pretty happy about the way it turned out: It looks trivially simple, but yet it supports almost all types of indexes. The only thing that it doesn't support are custom storage parameters.

What do you think about it? Does it do what you need? Does it make sense? Is it confusing?

(Also, the structure editor is now a bit more colorful. Primary keys are yellow, unique keys are blue, foreign keys are green.)

**Comment by swrobel** [comment]
Just spent some time playing with it and I think it's fantastic. It's exactly what I was hoping for (and have come to expect from Postico) - simple yet powerful.

**Comment by neverov** [comment]
Awesome!

**Comment by gangstead** [comment]
Just downloaded 1.1 and this feature looks nice.  Is there a way to get the sql for an existing index (what was shown before)?

**Comment by jakob** [comment]
@gangstead There is no way to view the SQL of an index at the moment. I just didn't find a good space to put it.

I'm considering adding a third section to the bottom switcher (Contents / Structure / SQL) that displays SQL of the table, indexes etc., but that is a separate issue.

**Comment by frozenfung** [comment]
In the first hand I search around in my Postico app but can not found any index suddenly I realize that I use an out-of-fashion version. After I re-install the newest one I discover the treasure! Thanks for developing & maintaining this awesome app!

**Comment by SeanFLynch** [comment]
I constantly get this error message when trying to load views after the latest update.

'Could not load table rows.
Query failed
PostgreSQL said: syntax error at or near "FROM"'

I've been advised that this is because of Redshift's new late binding views feature, described here - https://blog.fishtownanalytics.com/using-redshifts-late-binding-views-with-dbt-e735d80f9cfc

Any help on this would be appreciated.
