### ISSUE TITLE
Please revert the filtering shortcut 

### ISSUE THREAD

**Issue by xarg** [jakob/Postico#204]
The filtering of the table CMD+F seems to have become CMD+ALT+F (only it doesn't work on my machine).

I'm not sure how most people search, but I rarely scan the tables in the table list and most of the time I'm searching stuff on the table I selected. CMD+F was super convenient and "natural", it's like the number one feature for me.

Needless to say I'm super disappointed because of this change. The shortcut itself (CMD+F) doesn't seem to be used anywhere:

![screen shot 2016-04-13 at 14 34 23](https://cloud.githubusercontent.com/assets/94721/14493288/01e3b024-0185-11e6-91b5-6afe963aa5ca.png)

**Comment by xarg** [comment]
In the meantime I reverted to 1.0.5: https://s3-eu-west-1.amazonaws.com/eggerapps-downloads/postico-1.0.5.zip

**Comment by ecsos** [comment]
I kind of agree.  You can't use the filter shortcut when in query/terminal mode anyways.

**Comment by jakob** [comment]
I've had to change the Filter shortcut because it interferes with the standard "Find" shortcut that opens the Find & Replace panel. Right now Find & Replace only works in the query editor, but I'm planning to add Find & Replace functionality also to the table view and the sidebar.

For this reason I've unfortunately had to change the Filter keyboard shortcut.

However, if you disagree with my choice, you can override any keyboard shortcut in System preferences. Go to Keyboard -> Shortcuts -> App Shortcuts and add a custom keyboard shortcut for `Filter…`

<img width="780" alt="screen shot 2016-04-15 at 13 21 45" src="https://cloud.githubusercontent.com/assets/198305/14560005/11c20a16-030d-11e6-87e5-859ab2267271.png">

**Comment by jakob** [comment]
@xarg Is Cmd-Option-F mapped to something else on your Mac? What language/keyboard layout do you use?

**Comment by xarg** [comment]
Standard Qwerty/US keyboard. CMD+Option+F is not mapped to anything afaik.

**Comment by jakob** [comment]
@xarg I also have a US keyboard and Cmd-Option-F works fine. This is really odd. Does hitting Cmd-Option-F flash the menu in the menu item or does it beep? Is the menu item greyed out? Does using the Filter button work? What OS X version are you on?

**Comment by xarg** [comment]
`App Shortcut` override worked for me.
