### ISSUE TITLE
Show timings for individual queries when queries are run from query windows

### ISSUE THREAD

**Issue by rajofchennai** [jakob/Postico#217]
When multiple queries are run, It would be very helpful if the timing/running time of each query is shown below it.

**Comment by jakob** [comment]
This isn't easily possible, since the server doesn't tell me how long queries run. So the time I display includes network round trips, the time to receive results, etc. If I'd split the time up (eg. according to when I receive results for a query), then the first query would include the network lag, etc. This would lead to extremely unreliable results.

For this reason, I can't include timings for individual queries. If you want to compare queries, I recommend to use EXPLAIN ANALYZE. You can execute multiple EXPLAIN ANALYZE commands at once, and then compare the results by switching in the results switcher menu.
