### ISSUE TITLE
postico crashes when queries are cancelled

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#222]
Postico seems to crash every time a query is cancelled and some of the rows have already been transferred. 

To reproduce, just execute `SELECT * FROM "big_table";` and cancel the query after the first rows appear.

Cancelling queries while no data has been transferred works fine, e.g: `SELECT count(*) FROM "big_table";`.

**Comment by jakob** [comment]
Is it a crash or does it hang? If its the latter, can you try the build from issue #220?

**Comment by qwesda** [comment]
It's a hang. 

The build from #220 resolves this issue. But it seems to take 3 seconds for the cancel to be take effect. 

Definitely better than the hang though.

**Comment by jakob** [comment]
Postico needs to wait for the server to acknowledge the cancel request before sending the next query (otherwise the wrong query might be cancelled)

It can take a while for the confirmation of the cancel command to come through when the connection is saturated (which it likely is when downloading a large resultset)

**Comment by jakob** [comment]
Fixed in Postico 1.0.7
