### ISSUE TITLE
Automatically re-connect on query execution

### ISSUE THREAD

**Issue by Ga68** [jakob/Postico#225]
It'd be great if there was an option to auto re-connect such that when I run a query and have been disconnected from the server the program would automatically re-connect and then run the query.

**Comment by 0x414f** [comment]
+1 Dunno why more clients don't do this.

**Comment by qwesda** [comment]
Isn't this what postico already does? If I run a query from and the connection is not open it gets re-opened automatically.

I think this feature is in postico since 1.0, it has been very reliable for me. I leave postico open all the time and change network locations multiple time a day. The lost connections are handled pretty transparently for me.

**Comment by jakob** [comment]
Postico does reconnect automatically, the problem is detecting that the connection has been lost. 

There is a setting in the preferences to automatically disconnect idle connections, which helps when frequently changing networks, but it can cause issues when you use temporary tables, or change the search path etc.

**Comment by Ga68** [comment]
It's a pretty minor inconvenience, but it just requires me to to hit "run" on the query twice and then click okay. On the first run, it says "Error, disconnected" and then on the second run, it pops up the dialog to ask "Do you want to reconnect." The request is just to have the reconnect happen automatically on the first run without any dialog.

**Comment by Ga68** [comment]
The "Keep Connections Alive" setting in Preferences resolves this for me.
