### ISSUE TITLE
Problem editing multiline texts

### ISSUE THREAD

**Issue by ottob** [jakob/Postico#231]
<img width="345" alt="screen shot 2016-05-27 at 10 31 42" src="https://cloud.githubusercontent.com/assets/67104/15929840/a971b646-2e4f-11e6-9df7-08291e21367a.png">

When I press the down arrow to scroll down in the content I'm editing, Postico goes to the next row. Is this the expected behaviour?

**Comment by jakob** [comment]
Yes, this is how I designed it.

Since Postico doesn't differentiate between text selection and cell selection (like spreadsheet apps do), I wasn't certain how else to handle this (arrow key navigation is important when editing tabular data)

Maybe I should make arrow keys first navigate within the text, and only when it reaches the end, move to the next cell?

Do you have a better idea?

**Comment by ottob** [comment]
I expected it to work like google sheets. You enter "edit mode" when you double click and then you have to press esc-key to exit edit mode. But maybe this won't work. It is not an important issue for me so I have no problems if it stays the way it is.
