### ISSUE TITLE
'ORDER BY "ctid"' not  valid for Citus distributed database extension

### ISSUE THREAD

**Issue by michelp** [jakob/Postico#234]
Hello, a recently open-sources postgres extension, Citus, shards table data into a cluster of worker databases.  It is very slick.  The Postico client can connect to a citus master but when clicking on one of the tables gets an error:

"The server said: invalid attnum -1 for rangetable entry table_name"

This is due to the 'ORDER BY "ctid"' clause generated by Postico.  ctids are not valid for distributed tables are there would likely be many redundant values.  What is the purpose of the 'ORDER BY'?  Some guessing is that it provides the user with a more "stable" view of the table from run to run?  Does that buy much than just removing the order clause and returning rows in whatever order the database returns them?

**Comment by jakob** [comment]
Hi!

You are right, Postico sorts by `ctid` to provide a more stable view. However, Postico only does that when the table has no primary key. The reason for this is that otherwise Pagination wouldn't work. If the rows are not sorted, PostgreSQL will sometimes return the same rows with different OFFSET clauses (it's free to do so when there is no ordering)

You can disable automatic sorting in the preferences.

The annoying thing in this case is that Postico checks if the table has a ctid column before using it, but Citus apparently disallows using the column.

Redshift does something similar, so Postico has a special case built in for Redshift. Redshift is simple to detect using `SELECT VERSION()`.

Do you have an idea how to efficiently detect that a table uses the Citus extension?

**Comment by michelp** [comment]
Hello, I believe the best method might be to detect the citus extension in pg_available_extensions and then check the pg_dist_partition table for the existence of partitions for that table.  

select exists(select logicalrelid from pg_dist_partition where logicalrelid='<tablename>'::regclass);

**Comment by jakob** [comment]
OK, I was afraid that I would need a separate query like this. If possible, I'd really like to avoid executing extra queries like this, since the extra network round trip makes Postico slower for people who don't use Citus...

**Comment by lithp** [comment]
@jakob you can detect Citus itself by running:
`SELECT exists(SELECT * FROM pg_extension WHERE extname = 'citus');`

However in Citus only some tables are distributed, and others are regular postgresql tables. You could run this query to detect Citus, and only when Citus is installed run the first query on tables to see if they're distributed tables?

**Comment by lfittl** [comment]
@jakob I'm curious as a bystander to this issue (fan of Postico, also working on Citus amongst other things) - couldn't you match on the error thats returned (and then use the same fallback that you use for Redshift), rather than checking for Citus separately?

**Comment by jakob** [comment]
@lfittl that's a good idea. I'll see if I can do that. I hope they don't change the error message...

**Comment by lfittl** [comment]
@jakob Yeah, I think the real fix is probably for Citus to allow the query (since you're merely checking for existence) - but I'm fairly certain there is a technical reason inside Postgres as to why thats not done today.

Checking for the error (maybe matching on `invalid attnum`) seems like the easiest workaround for now, at least from my perspective.

**Comment by jakob** [comment]
Thanks to everyone for the helpful comments, but according to the issue linked above, it looks like Citus was faster than me -- they fixed it. I don't know how long it'll take for the fix to propagate into a released version of Citus, so let me just restate that there is a work-around:

**Uncheck the "Always Sort Tables" command in the preferences.**

This will allow you to at least view sharded tables. Editing is still not possible, I'll have to investigate this issue in more detail.

**Comment by lithp** [comment]
@jakob We're just now wrapping up the next release and, no promises, but hope to release it within the next few weeks.
