### ISSUE TITLE
Structured Copy from Results

### ISSUE THREAD

**Issue by mehcode** [jakob/Postico#245]
Several times I'd like to do a quick copy-paste to show some data in Slack but the default copy-paste leaves a lot to be desired. 

If we could get the copy to be aligned or perhaps a new copy special "Copy as Markdown (table)"

**Comment by jakob** [comment]
Since version 1.0.7, Postico copies tables in RTF format by default. So if you copy data from Postico, and paste it into Pages / TextEdit / Numbers, you'll get a nicely formatted table. I assume that Slack doesn't support rich text?

I can see a use case for copying in other formats, eg. "Copy as HTML" might also be useful. Since Markdown supports inline HTML, that should also work for Markdown. As far as I know, Markdown has no Syntax for tables. Or does Slack have some extension for tabular data in Markdown?

**Comment by mehcode** [comment]
> Since version 1.0.7, Postico copies tables in RTF format by default.

Just tested in not slack, and you're right. It works nice there. Slack does not support RTF.

---

As for my original request.. from further poking I don't see a way to get Slack to display a table. 

Thanks for the tip on RTF as I can paste that into Excel / Sheets (Google) and it will separate into cells and then I can share that. Not as quick but largely better than what I could easily do before.

**Comment by mehcode** [comment]
@jakob Just came across wanting this but in a slightly different way: `Copy as JSON / YAML / etc.`. JSON by itself would be amazing.

**Comment by jakob** [comment]
I've added two new Copy Special commands: JSON and HTML table.

You can try a development build here:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1500.zip
