### ISSUE TITLE
UI: add a wrap option into the settings

### ISSUE THREAD

**Issue by petersirka** [jakob/Postico#26]
I work with Postico everyday and it would be great if the Postico settings will contain the wrap option for headers and values with a minimal column width e.g. 120px. It's better for reading.

![screenshot](https://cloud.githubusercontent.com/assets/2414252/8564386/a3da4b16-254b-11e5-8488-93704e600e85.png)

What do you think about it?
Thanks.

**Comment by jakob** [comment]
I'm not sure I understand correctly. Do you suggest that Postico should clip the column title (like this: `idcatgo...`) when the column is less than 120px wide?

I agree that wrapping column titles are not pretty, but I always found clipped column titles extremely annoying.

**Comment by petersirka** [comment]
`idcatgo...` yes and you're right. I don't want to add it as default settings, only as option. Developers who work with DB know their columns. Thanks.

__PGAdmin:__
![screen shot 2015-07-08 at 9 07 07](https://cloud.githubusercontent.com/assets/2414252/8564902/b9f57056-2550-11e5-8dd0-c07b0128407e.png)
---
__SQLPro for MSSQL__
![screen shot 2015-07-08 at 9 06 25](https://cloud.githubusercontent.com/assets/2414252/8564912/ccd39f18-2550-11e5-9871-c3af062ec958.png)

**Comment by danillos** [comment]
Hi @petersirka, I prefer `idcatgo...` too.

**Comment by jopotts** [comment]
I would prefer no wrapping too. More importantly, the fields in the table should not wrap in my opinion, and rows should be a single char high, not two. You have the right sidebar to view details if needs be so no need to clutter the table. Also, the grey/white stripe of Sequel Pro's table is nice rather than dividing with a line. Thanks for the great software!

**Comment by jakob** [comment]
I've redesigned the table view a bit, and turned off wrapping in the column headers.
http://eggerapps-downloads.s3.amazonaws.com/postico-2015-07-21.zip

I'm considering adding a preference for the row height, so that people can also turn off wrapping in the content area. That's a bit more work, so I'm saving it for later.

**Comment by jopotts** [comment]
The headers are looking good. Please please make the table layout single line (with grey banding). Make it like Finder list view. No need for a preference setting even. Postico is the best postgres app available for simply browsing data, but this would really be the icing on the cake! Thanks!

**Comment by himikk** [comment]
Please make grig rows single line. It's very critical.

**Comment by petersirka** [comment]
@himikk +1

**Comment by RuShire** [comment]
Agree with @himikk, please fix, this is very annoying.

**Comment by wellsoliver** [comment]
Agreed but in a polite and loving manner

**Comment by jakob** [comment]
I've now added an option to configure the number of lines per row in the table view, so you can change it to a single line. Prerelease build:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1309.zip

I'm planning to add an option for alternating row colors instead of grid lines as well, but I first need to redesign the preference window which ended up pretty messy.

**Comment by petersirka** [comment]
@jakob GREAT, really great!
Thanks

**Comment by jopotts** [comment]
Lovely! Thank you! Preference window seems fine as it is for now. Alternating colors will be nice...

Comparison with SequelPro: http://f.cl.ly/items/3k0R2N2c3f1R080p1s2j/Image%202016-02-05%20at%2012.06.53%20pm.png

**Comment by jakob** [comment]
I've now implemented all the features requested here:
1) no more wrapping in table header
2) preference for setting number of lines per row
3) added a pref to use alternating row background colors

I'm marking this issue as fixed now.

Please try the prerelease and let me know if this works for you!
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1334.zip

Thanks for all of your feedback!

**Comment by jakob** [comment]
This issue is resolved in Postico 1.0.4
Download here: https://eggerapps.at/postico/
