### ISSUE TITLE
Option to show views in a sub folder

### ISSUE THREAD

**Issue by nathanpalmer** [jakob/Postico#285]
I would love an option that would put all views showing in the sidebar in a subfolder. This would significantly reduce clutter in many databases that we work with.

![image](https://cl.ly/2f3F3f1K1m0n/Screen%20Shot%202016-10-21%20at%204.10.30%20PM.png)

I'd imagine that if you enable this option it'll throw them all in a folder very similar to `pg_catalog` and `information_schema`

**Comment by jakob** [comment]
Is there a reason why you don't just put them all into a schema?

**Comment by Ricardo-C-Oliveira** [comment]
Some of our databases also have a ton of views, it is fine once you embed in you head which color are the regular tables and which color are the views. I think that to have the views within the schema folder is very important, but maybe a inner subfolder, similar to how pgadmin does, could help organize "view intensive" dbs a little better.

**Comment by nathanpalmer** [comment]
> Is there a reason why you don't just put them all into a schema?

I wouldn't want to put it in a schema just for the purpose of making it easier to work with in Postico. There might be some other reasons to consider a schema but that's a broader thing our team would have to look at.

**Comment by jakob** [comment]
I've thought about this, and I don't want to offer any additional customisation for the sidebar at the moment. The code is already complex enough, and I the number of configurations I need to test grows exponentially as I add settings, so unfortunately I can't accommodate every use case.

I definitely don't want to change the default behaviour, since a pgAdmin-like interface is very confusing for newcomers.

So I'd like to thank you a lot for your suggestions, but I'm not going to implement this now.
