### ISSUE TITLE
App crashes when I try to edit a table

### ISSUE THREAD

**Issue by erinconeal** [jakob/Postico#298]
Here is the crash log:

[crash.txt](https://github.com/jakob/Postico/files/631550/crash.txt)

**Comment by jakob** [comment]
Thanks for the crash log. It looks like the table has a "NULL" schema name; I'm not sure how that could happen. If you have any additional details how this happened, I'd love to hear them. I looked through my source code and just couldn't figure out how this could possibly have happened.

In any case, I've added additional type checking to Postico to catch this case to avoid crashes. You can download the latest build here:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1539.zip

Would love to hear if this fixes your issue, and if you have any further details how the crash happened.

**Comment by jakob** [comment]
I'm closing this issue for now, since I couldn't find out what exactly happened. It's most likely related to window restoration, but I can't know for certain.

In any case, the additional checks I've added to the table structure view should prevent this crash in the future. There might still be some odd behaviour, but it should be fixable by changing the schema in the schema popup.

Please reopen the issue if this problem occurs again!
