### ISSUE TITLE
app crashes when trying to copy a file into a bytea field

### ISSUE THREAD

**Issue by remys** [jakob/Postico#299]
Version 1.0.10 (1514)
navigate to a record having a bytea field
in the the rightmost pane, navigate to the bytea field and click "scan" button
select a pdf file in the file dialog, click ok
-> Postico crashes

**Comment by jakob** [comment]
Thanks for reporting this issue. I think I found it.

You can download the latest build here: 
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1539.zip

If you are curious: Postico pipes data to the `file` command to guess file types. `file` closes the pipe as soon as it has determined the file type. When that happens, NSFileHandle throws an exception, which I didn't catch. This means that Postico crashed when adding large files. I only tested with small files :(

**Comment by remys** [comment]
Hi Jakob,
Many thanks for your prompt feedback.
And yes, for “small files” (a few kB), the fix works fine, but using bigger ones (1,8 mB) this version still crashes, unfortunately
Regards
Remy

**Comment by jakob** [comment]
This issue should now be fixed in Postico 1.1, available on my website. (Update for Mac App Store Customers is coming soon)

In case you still run into similar problems in Postico 1.1, please reopen this issue. When reporting crashes, please always check `~/Library/Logs/Diagnostic Reports/` for crash reports!
