### ISSUE TITLE
Evaluating Postico

### ISSUE THREAD

**Issue by oakstreetsoftware** [jakob/Postico#301]
I'm running the evaluation software, so maybe I'm missing some things.

Is there a way to view/alter the permissions on a table/view ?
Is it safe to assume that I can have more than one window open in the licensed version ?
Would it be possible to remove tables and views to which I do not have 'select' permission ?

I know the tool is designed for admins, but I want to recommend it to one of my clients who is not a DB admin, but is quite computer savvy and I'd like for him to have access to views that I create for him, so he can run simple queries and use filters to select data sets for importing into a spreadsheet.

It's a nice tool. I didn't have any problems with it, while poking around the database. It is responsive and doesn't hang or crash. What I really need is a reporting tool, but this is a pretty close match and the price is very low. It also looks like the support is very good. :)

**Comment by jakob** [comment]
> Is there a way to view/alter the permissions on a table/view ?

Unfortunately not yet. For permission editing you need to use the query view (tedious) or another tool.

> Is it safe to assume that I can have more than one window open in the licensed version ?

Yes :)

> Would it be possible to remove tables and views to which I do not have 'select' permission ?

No, but that would be a good idea for a future feature. (People have complained about this before)

> I know the tool is designed for admins, (...)

My target audience are not just developers, but also data analysts and business users. With updatable views, you can even use Postico for some simple data entry tasks, and I use it myself for some light reporting (using views). It's a very generic tool, so it won't fit every use case, but if the functionality is sufficient, it's a lot cheaper to use something like Postico instead of developing a custom web app.
