### ISSUE TITLE
Pretty print for jsonb should be an option

### ISSUE THREAD

**Issue by doekman** [jakob/Postico#306]
Go to table view of a table with jsonb type, select a row, and open the right-side pane to see the row data vertically. In the jsonb field, there is a dropdown with three options: NULL, DEFAULT and Pretty Print JSON.

The Pretty Print JSON option makes no sense for JSONB, because the Pretty Printed version is not saved, just the data. However, pretty printed json is nice to have.

So my suggestion (feature request) is to make this a toggle-field to always show the data pretty printed (or not, depending if it's selected or not). Also, change detection should be on data level, not on string level (pretty printing jsonb is no change). 

I think it would be a sensible default for this option to be stored on connection-level, so the option persists for all jsonb fields within that connection. Or maybe even on application level.

**Comment by doekman** [comment]
Hi Jacob, have you given this any thought?

**Comment by jakob** [comment]
Yes, I've been thinking about this. I think that Postico should always show JSONB pretty-printed in the sidebar. I wouldn't even make it a preference. But it probably shouldn't be pretty printed in the grid view, because then you'd only see opening braces most of the time -- not very useful.

A problem with pretty-printing is that text wrapping tends to break the layout -- so I should probably use some automatic indenting for wrapped lines. This isn't so easy, because then it's no longer just a simple text field...

And then there's a very subtle issue with parsing JSONB values, because PostgreSQL treats numbers in JSONB a bit odd, so some rounding issues might pop up -- I haven't fully thought that through yet.

**Comment by doekman** [comment]
I can wait; sometimes good features take time.

Don't you consider horizontal scrolling, so you don't need soft-wrapping?

**Comment by qwesda** [comment]
While pretty printing does not make a lot of sense for the grid view, syntax highlighting would be very helpful here. This would make quickly parsing lots of rows visually much more easy.

A fully pretty printed version would be great fit for a preview window like the one mentioned in #387.
Bonus points for collapsable arrays/dicts.

**Comment by martinjankoehler** [comment]
Hey @doekman , @qwesda ,

we have been working on some improvements regarding Postico JSON,
summarized in this issue:
https://github.com/jakob/Postico/issues/570#issuecomment-845312674

Any feedback or issues discovered are highly appreciated!

Best regards,
Martin

**Comment by martinjankoehler** [comment]
Postico 1.5.18 was released today [(download)](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-1.5.18.zip) and contains some JSON fixes, including pretty-pretting of `jsonb` values.
