### ISSUE TITLE
manual insert of data does not check the constraints of the primary key

### ISSUE THREAD

**Issue by jkokatjuhha** [jakob/Postico#309]
I have a following create table query :

`create table lala1(datestamp date PRIMARY KEY,hours integer,country varchar(255))`
datestamp is a _primary key_.

When I enter manually over the _Postico Interface_ (Row+) some data, and have the same datestamps, it does not throw me an error that I try to enter the data that violates violates unique constraint of the primary key.

So, in fact, if I enter manually some data in Postico, it doesn't check if it violates the constraints. Also, if I do it via "SQL QUERY", it does not check the primary key constraint.

```
drop table if exists support_tracking.lala1;
create table support_tracking.lala1(datestamp date,hours integer  NOT NULL UNIQUE,country varchar(255));

INSERT INTO "support_tracking"."lala1"("hours") VALUES(1);
INSERT INTO "support_tracking"."lala1"("hours") VALUES(1);
```

```
DROP TABLE
CREATE TABLE
INSERT 0 1
INSERT 0 1
INSERT 0 1
```

Is there a work around ?

![bildschirmfoto 2017-01-10 um 12 29 55](https://cloud.githubusercontent.com/assets/2404796/21804682/89da81fc-d730-11e6-9b8a-a25fe615ba35.png)
![bildschirmfoto 2017-01-10 um 12 30 01](https://cloud.githubusercontent.com/assets/2404796/21804683/89fba9a4-d730-11e6-86e4-4f9d3c2ec4b4.png)

**Comment by jakob** [comment]
Postico doesn't check constraints; the server should do that. Normally when you do that, an error message should appear from the PostgreSQL server.

Could it be that you are using Amazon Redshift? Redshift doesn't enforce unique constraints -- presumably because enforcing unique constraints would cost a lot of performance.

(And annoyingly, it's also really hard to delete duplicate rows in Redshift. You can only delete both and insert a new one again.)

**Comment by jakob** [comment]
I'm closing this issue for now, since I don't think it is a problem in Postico. Feel free to reopen it if you have further information to add.
