### ISSUE TITLE
Ctrl+Enter inserts \u2028 instead of newline

### ISSUE THREAD

**Issue by j2kun** [jakob/Postico#314]
Version 1.0.5 (1353)
OS X (El Capitan) 10.11.3

Editing a text field in line and inserting newlines (via ctrl+enter, since enter and command+enter and shift+enter all don't work) inserts `\u2028` (Unicode Character 'LINE SEPARATOR') instead of a newline.

This caused me a mild headache, since various python json serializers (I'm using Django) treat this character differently. Why is it this way?

**Comment by j2kun** [comment]
Update! Option+Enter inserts newline and Control+Enter inserts `\u2028`

Still, this is... strange behavior since there's no way to tell what you did from the Postico interface.

**Comment by jakob** [comment]
Hi!

This is the standard behavior for Cocoa text fields. But interesting! I didn't know there was a way to insert the LINE SEPARATOR character; it never occurred to me to try ctrl-enter.

I've been thinking about making special whitespace characters visible (another candidate would be the non breaking space), but this is surprisingly hard in Cocoa, especially since I am using many different ways to draw text.

Do you have an idea what I could do to make option-return more discoverable?

**Comment by j2kun** [comment]
Maybe disable Ctrl+Enter or have a modal when saving a text field with \u2028 in it that asks you if you really want to do that?
