### ISSUE TITLE
Row not encoded, can't export reports

### ISSUE THREAD

**Issue by yascat** [jakob/Postico#319]
Hi, I cannot seem to export ANY report from postico due this error message. I have uninstalled and reinstalled and the error still exists. Please can you help.

Thanks, 
![screenshot 2017-01-30 14 22 15](https://cloud.githubusercontent.com/assets/25438258/22434126/c389bae8-e712-11e6-88ab-6286cb73d634.png)

**Comment by jakob** [comment]
Usually this happens when you try to export files in MacRoman or ISO Latin 1 encoding, but the data contains characters that are not supported by that encoding. If that is the case, please use UTF-8 instead.

If this error happens with UTF-8, can you try to narrow down the problematic column or row? If you perform a "binary search" you should quickly find out which row/column contains the problematic data (execute the select with only the first half of the columns, then with the second half of the columns, etc., until you find which column is the problem).

**Comment by jakob** [comment]
I've changed the error version displayed so it's clear that you have to use Unicode if this happens.

Prerelease: https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1578.zip
