### ISSUE TITLE
Temp tables should not be opened automatically

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#350]
When postico tries to restore the previous table view it should not try to switch to a table in the `pg_temp` schema since it won't be there (or not accessible).

**Comment by jakob** [comment]
I've started to work on this:

https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1616.zip

There is a minor issue remaining: the left sidebar width is restored incorrectly when the right sidebar was opened. I need to have a look at this.

**Comment by qwesda** [comment]
The 1616 build seems to behave identically to the 1.1.1 version.

**steps to reproduce**
- open db
- run create temp table query
- reload connection
- switch to temp table 
- hit `cmd + t` or `cmd + alt + n`  -> yellow warning message `Could not load table rows. Query failed PostgreSQL said: cannot access temporary tables of other sessions`

**expected behavior**
- the new window/tab opens the same view as if the db was opened from the favorites window, i.e. 
the db overview

**Comment by jakob** [comment]
Thanks for the detailed follow-up. Now I understand -- I thought you were talking about window restoration after quitting and restarting Postico, which was also broken.

Since I usually connect with a superuser for testing, I wasn't aware of the issue you described (a superuser can access temp tables from another session).

Anyway, I've now also fixed the issue when using the "new window" or "new tab" commands.

Please try the release candidate build from issue #354 and let me know if it now works as expected!

**Comment by qwesda** [comment]
works as expected for me now.

Is this behavior special-cased for superuser connections? While this is not how I use temp tables maybe some people would appreciate the old behavior if they use superuser connections ...

**Comment by jakob** [comment]
I made no special case for superuser connections.


I didn't think much about this case before, but now that I did I don't think opening temp tables from a second connection is something you should do, even with a superuser. You can still do it explicitly by right-clicking and holding down the cmd-key and selecting "open contents/structure in new window".

But the default behavior should be that temp tables only appear on the connection that they were created on.

Anyway, thanks for bringing this case to my attention; your frequent input is invaluable!

**Comment by qwesda** [comment]
thanks!
