### ISSUE TITLE
Problem with connecting to PostgreSQL through an SSH tunnel

### ISSUE THREAD

**Issue by knozharov** [jakob/Postico#359]
Hi.

My colleagues and I have been using Postico for a while and are really happy with it.
However, it has some limitations when it comes to connecting it to an SSH tunnel.

We have the following issue:

I open a channel in the usual way, pointing it to the port of the remote host I am connecting to and specifying the localhost's port I will use for the Postico connection.
The problem is that on the remote host I have two PostgreSQL instances running on two ports: 5432 and 5433. I guess the default behavior of Postico when opening a connection to the remote DB is to use port 5432. However, I need to somehow point it to 5433.
Is that possible with the current release or it needs further development?

Thank you in advance for your cooperation.

**Comment by jakob** [comment]
Hi!

I am not sure I understand correctly. Are you using Postico's built-in SSH support, or are you creating a tunnel manually from the command line?

**Here's how to use Postico's built-in SSH tunnelling feature:**

<img width="405" alt="screen shot 2017-03-31 at 14 46 43" src="https://cloud.githubusercontent.com/assets/198305/24551184/dc969356-1621-11e7-821d-1f85d82cb1f7.png">


1. From the "Options" popup, select "Connect via SSH"
2. In the "SSH Host" and "Port" fields, type the hostname and port of the SSH server
3. In the "Host" field, type the host name of the database server, **from the point of view of the SSH server**. If the SSH server is the database server, type "localhost".
4. In the "Port" field, type the port of the database server.

If you use Postico's built in SSH tunnel feature, you don't need to worry about the ports on the local side of the tunnel. Postico will pick a random unused port.


**If you want to manually open the SSH tunnel:**

In this case you choose the db server port when you open the tunnel:
`ssh -L localport:db_host:db_port ssh_host`

So in your case you'd do something like this:
`ssh -L 12345:db_host:5433 ssh_host`

And in Postico you disable SSH and just connect to Host: localhost, Port: 12345 (where instead of 12345 you can also pick any other unused port on your Mac)

**Comment by knozharov** [comment]
Thanks for the prompt response. I couldn't reply sooner though.

So, I am creating a tunnel manually from the command line.
Then I am pointing the DB connection to the tunnel using **localhost** as the host and the designated local port. I also specify the username, password, and database to connect to.

I am aware of the **Connect via SSH** functionality of Postico but unfortunately cannot use it since my private key was generated using ECDSA. I read in another open issue here that currently Postico cannot use it for SSH tunnels as it is not supported by LIBSSH2 yet.

Would you confirm that I would be able to use the **Connect via SSH** if I use a private key generated using RSA, for instance?

**Comment by jakob** [comment]
Hi @knozharov!

As I stated above, when you use a manual SSH tunnel, you specify the remote port (=PostgreSQL server port) on the command line.

To answer your second question: yes, if you use RSA keys, you can use Postico's "Connect via SSH" function. However, the server must also have a RSA host key (which is enbled by default). If the server is configured to only use EC keys, you can't connect with Postico. All the ciphers and schemes supported by Postico are listed on the libssh2 homepage: https://libssh2.org

**Comment by knozharov** [comment]
Thanks. I will try changing the keys then :)
