### ISSUE TITLE
Sorting rows by NULLable column puts NULL above real values

### ISSUE THREAD

**Issue by gajus** [jakob/Postico#371]
I have a column `timestamp with time zone` that is `NULL`able. Sorting rows by this column in a descending order using the content view puts NULL values above the timestamp values.

The expected behaviour is `[any non NULL value]` > `NULL`.

**Comment by jakob** [comment]
By default PostgreSQL treats NULL values greater than all other values. See the docs for details:
https://www.postgresql.org/docs/9.6/static/sql-select.html#SQL-ORDERBY

I guess it would be nice if there was a way to specify `NULLS FIRST` or `NULLS LAST` when sorting. At some point I might add this as a feature.

Right now, you can use filters as a workaround to show or hide NULL values as required.

**Comment by gajus** [comment]
> By default PostgreSQL treats NULL values greater than all other values. See the docs for details:
https://www.postgresql.org/docs/9.6/static/sql-select.html#SQL-ORDERBY

That might be true in the Postgres world, but client behaviour does not need to map 1-to-1 with the standard. From the UX perspective, it does not make sense to tread NULL as greater than other values as that makes sorting of NULLable fields useless (unless you filter out the NULLs).

**Comment by gajus** [comment]
This issue annoys me every single day.

Can a NULLable column simply have 3 states?

* Click once, sort by ASC,
* Click +1, sort by DESC,
* Click +1, sort by DESC NULLS FIRST

**Comment by MatthiasWinkelmann** [comment]
@gajus You can set the order when creating the index:
![screenshot 2018-11-16 at 13 15 26](https://user-images.githubusercontent.com/10232033/48620814-b75afc80-e9a1-11e8-9a00-da380e40ce1b.png)

The default is annoying, indeed. But this would seem to be a problem in PostgreSQL first. I would be quite surprised if the client came with a default different behaviour than I was used to. I'd be somewhat **positively** surprised, in this case. But others might not appreciate it. There must be _someone_ out there who wants NULLs first, right?

**Comment by jakob** [comment]
I added a way to sort by DESCENDING NULLS LAST in Build 9666. To get there, right click the column name and select "Descending (Nulls Last)".

![Bildschirmfoto 2023-11-14 um 14 03 55](https://github.com/jakob/Postico/assets/198305/82e22728-2ab9-4cf1-a1f7-346be3035511)

I left the default on "Descending, Nulls First" because it is the opposite of "Ascending Null Last", so clicking the button just reverses the sort order. Someone not familiar with the NULLS FIRST / LAST command would be very confused why clicking the button again would reverse only part of the table.

(Also, Postico supports sorting by multiple columns now)

You can download the latest build from [the changelog](https://releases.eggerapps.at/postico2/changelog?update_channel=1)
