### ISSUE TITLE
Open source Postico

### ISSUE THREAD

**Issue by gajus** [jakob/Postico#374]
Just a thought, but it would be beneficial to the entire community if Postico was open-sourced.

Open-sourced does not mean "free", though. You could still have a commercial license and any big corporations would respect that (that said, few big companies use OSX as their development environment).

People who are not willing to pay for it will find ways to get a free version anyway. I've done a quick query across multiple Warez websites, and they all have NULLed Postico version up for grabs. (Happy to share links if of any relevance, not there is much you can do about it.)

In this respect, I really like https://github.com/luin/medis model. Users can either buy Medis or build it themselves.

Similarly, Postico could adopt a donation model. https://sequelpro.com/ is doing amazing in this respect. Have a look at https://sequelpro.com/donate. I've personally donated to Sequelpro project many times in excess of what Postico license costs.

The primary motivation for open-sourcing Postico is to enable community driven development.

**Comment by gajus** [comment]
@jakob I was going to say that Sequepro has 10+ contributors who have contributed 1k+ lines of code, but you already know that as you are one of the contributors. :-)

https://github.com/sequelpro/sequelpro/graphs/contributors

**Comment by jakob** [comment]
Thanks for your suggestion!

I've thought about making Postico Open Source, but I strongly doubt that I could make a living from it if I did. I don't know how much money the Sequel Pro folks are making from donations, but back when I contributed it was developed exclusively by volunteers, and donations were negligible. Nobody had time for important new features (like PostgreSQL support) because nobody could afford to put in the time necessary to develop that.

You say that Sequel Pro is now "doing amazing" with regards to donations. Do you have any insights into how much they are making? Are they actually paying developers from their donations?

Just from their donations page, I see that 30 people donated for Sequel Pro in March. If these people donated the suggested amount of $10 - $20, that would only be $300 to $600 per month. For that money, you could maybe hire a student to work for 5 hours a week, but that's not sustainable.

**Comment by gajus** [comment]
> You say that Sequel Pro is now "doing amazing" with regards to donations. Do you have any insights into how much they are making? Are they actually paying developers from their donations?
> 
> Just from their donations page, I see that 30 people donated for Sequel Pro in March. If these people donated the suggested amount of $10 - $20, that would only be $300 to $600 per month. For that money, you could maybe hire a student to work for 5 hours a week, but that's not sustainable.

The "amazing" is based on the same dataset and similar estimate. My guess is that their donations average in the region of 1000/ month.

As an open-source, making USD 600-1000/ month in donations is a lot. However, if Postico is your full time job/ income source, thats not an option.

Nevertheless, I'd reach out to have a few companies who you know are using Postgres (i.e. Postico clients) and see whether they have a model for supporting open-source projects that they depend on. It cannot be too hard to secure 10-20 donors that'd be willing to donate USD 100/ month. For a SMB, thats a water drop in a sea.
