### ISSUE TITLE
Switching between tables from navigation sidebar

### ISSUE THREAD

**Issue by gintsmurans** [jakob/Postico#40]
It would be nice if switching between tables from navigation sidebar would remember whether content or structure view was open and would then open that. Currently it always opens Content at first.

**Comment by carltongibson** [comment]
> There's an undocumented feature that might help: hold down alt while clicking a table to show the structure view instead of content view.
> https://github.com/jakob/Postico/issues/86#issuecomment-148218207

That helps some — but doesn't work with Arrow Keys

+1 for this — if that helps.

**Comment by jakob** [comment]
I've now removed the alt key shortcut (since it was impossible to discover) and instead now always open tables in the last used mode. I don't save state per table, since I assume that when you are looking at structure it is likely that you want to look at another table's structure etc.

If you'd like to switch to a different view, you can use the context menu to directly jump to contents or structure.

You can try out the latest build, and I'd love to hear your feedback:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1316.zip

**Comment by gintsmurans** [comment]
This is great news. Alt really was hard to discover. Thanks.

**Comment by qwesda** [comment]
Works as expected. Switching wildly between structure/content and tables/views/query didn't cause an issue.

**Comment by jakob** [comment]
This issue is resolved in Postico 1.0.4
Download here: https://eggerapps.at/postico/
