### ISSUE TITLE
Consider using ssh config

### ISSUE THREAD

**Issue by adisos** [jakob/Postico#432]
My ssh config (~/.ssh/config) looks like this:
```
Host sshablehost
  Hostname sshablehost.example.com
  User root

Host privatehost
  User root
  ProxyCommand ssh -o 'ForwardAgent yes' sshablehost 'ssh-add && nc %h %p'

Host superprivatehost
  Hostname superprivatehost.example.come
  User root
  ProxyCommand ssh -o 'ForwardAgent yes' privatehost 'ssh-add && nc %h %p'
```

So I can ssh into `sshablehost`, from this host I can access `privatehost` and then I can ssh into `superprivatehost`. I can't ssh directly to `privatehost` and `superprivatehost`.

With above ssh config I can ssh into `superprivatehost`.

![image](https://user-images.githubusercontent.com/592907/30319547-ff20b6a4-97d1-11e7-9023-e2005cce761a.png)
But postico says it doesn't know about `superprivatehost` host. I think postico don't know about `~/.ssh/config` file.

**Comment by meeDamian** [comment]
I would also love to see that. Looking into `~/.ssh/known_hosts` would also be great :).

**Comment by jakob** [comment]
At the moment, I can't add support for this for two reasons:

1) Postico is sandboxed, and can't read `~/.ssh/config`

2) Even if it had an exception for that file, Postico uses libssh2, which does not support all the OpenSSH config settings.

3) Even if libssh2 supported all the settings from OpenSSH, things like ProxyCommand are fundamentally incompatible with sandboxed apps, since ProxyCommand could do anything at all and would render the sandbox pointless.

So for know, Postico will continue to ignore  `~/.ssh/config`. If at some point I stop sandboxing Postico, and switch from libssh2 to OpenSSH, support for that file would be automatic. But that would be a major change, and I am not sure if the upsides are worth the downsides (no more Mac App Store).

@meeDamian Postico does look at `~/.ssh/known_hosts`. However, system SSH uses ECDSA keys by default, which Postico doesn't support yet, so it can't use the keys from known_hosts and has to ask the user to check the RSA host key instead.

**Comment by meeDamian** [comment]
Thanks for clarifications!

**Comment by julienroger** [comment]
I've dealt with this by opening ssh tunnels manually as @jakob described in #359.

I wonder if it's possible to include ssh tunnelling hooks, perhaps in a postico config file (and replicate some of your `~/.ssh/config` file?
