### ISSUE TITLE
"is distinct from" filter option doesn't work for Redshift

### ISSUE THREAD

**Issue by troex** [jakob/Postico#446]
To be honest I liked the previous option more `<>` "is not exactly" (or how it was named), but the point that now it's impossible to build "not equal" statement with filters on Redshift without using "custom" statement.

```
Could not load table rows.
Query failed
PostgreSQL said: Not implemented
Detail: 
  -----------------------------------------------
  error:  Not implemented
  code:      1001
  context:   'false' - Unknown pg type - 312
  query:     9870156
  location:  cg_expr.cpp:4532
  process:   padbmaster [pid=29249]
  -----------------------------------------------
```

```
> SELECT VERSION();
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.1497
```

**Comment by jakob** [comment]
Thank you for posting this issue. It’s pretty embarassing that I haven’t discovered this issue since August.

I have switched from `<>` to `is distinct from` since it is more likely to be what users expect — even though I know how `<>` works, I was surprised by its behaviour on occasions.

I don’t want to offer both options, because that would be very confusing.

I will change the filter to use `(x <> 'val' or x is null)` on Redshift.


If you don’t want NULLs, you could explicitely exclude them with a second filter.

Would this work for you?

**Comment by troex** [comment]
I usually use `x <> 'val'` when I mean "is exactly not", but it might be better to use "is equal" instead of "is exactly", then "is not equal" is more clearly just `<>`.

If you don't want to change exact/equal and logic behind them, then your solution is definitely better for Redshift.

PS. I'm not native English speaker but "is exactly" always sounded strange to me in terms of SQL or any programming in general.

**Comment by jakob** [comment]
Yes, that's a good point. "is exactly" sounds a bit odd (I am also not a native English speaker). Maybe I should just use an `=` sign, since that is what is going on...
