### ISSUE TITLE
jsonb column values escaped when Copy Special > Copy JSON

### ISSUE THREAD

**Issue by daviestar** [jakob/Postico#448]
Actual output:
```json
[
  {
    "id" : 1,
    "body" : "{\"test\": \"test1\"}"
  }
]
```

Was hoping for:
```json
[
  {
    "id" : 1,
    "body" : {
      "test": "test1"
    }
  }
]
```

**Comment by martinjankoehler** [comment]
Hey @daviestar ,

thanks for reporting this issue.

We have fixed the JSON representation for JSONB field types, the value now becomes proper JSON instead of a string.

The next Postico 1.5.18 release will contain this fix, in the meantime this preview build is available for testing:
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8035.zip

The latest Postico 2 Beta update (8038) also contains this fix and is available using the built-in updater,
or as a direct download: https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8038.dmg

Closing this issue now, please feel free to re-open or add a new issue should any other problems occur.

Best regards,
Martin

P.S.: 
- we've also added Copy Special support for JSON lines format
- Postico 2 full table export feature now also supports JSON (table sidebar context menu `Export <name>…` or main menu `File > Export <name>…`)

**Comment by martinjankoehler** [comment]
Postico 1.5.18 was released today [(download)](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-1.5.18.zip)
