### ISSUE TITLE
Feature to extract SQL from existing table

### ISSUE THREAD

**Issue by themccallister** [jakob/Postico#454]
First of all, thank you for the _BEST_ postgreSQL client out there... This is always a must have for me on any project! Keep up the great work!

One feature that I love is the fact you can preview the SQL before creating a table in Postico. One really amazing feature would be allowing a preview of the SQL used to create a table (based on an existing table).

Again, thank you for this app! Absolutely amazing!

**Comment by jakob** [comment]
Yes, that would indeed be very nice! Unfortunately it is not a trivial feature, since PostgreSQL does not have any server side functions to generate the CREATE TABLE statement -- we'll need to look at the catalog tables and build the query.

Since this request is very similar to #34, I'll mark it as a duplicate.

Thanks for the feedback!
