### ISSUE TITLE
view definition vanishes on click

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#464]
In the current version (and the dev build 2051) the view definition vanishes when it is selected with the mouse. On `mouse_down` the text is still displayed (but without syntax highlight) and on `mouse_up` the text vanishes completely. The text returns when selecting another input component (or by randomly clicking in the view definition field).

I also noticed that the view definition field is not accessible by hitting `TAB`. After the table comment input field the focus goes to the first column name.

**Comment by jakob** [comment]
Hmm. I can confirm that there is something funny going on with regards to hitting tab, but it behaves different on my machine. I can't leave the view definition field, but I am able to enter it.

I'm on macOS 10.12.6. What version of macOS are you on?

How you connecting to the PostgreSQL server?

**Comment by jakob** [comment]
Further testing shows that tabbing seems to work on macOS 10.13. I can't reproduce the text vanishing bug. It's probably related to syntax highlighting. I've seen text disappear from text views when the font could not be found, but I'm not sure why this would happen in this case.

Can you also let me know what database server version you are connecting to?

**Comment by qwesda** [comment]
I'm on macOS 10.13 and the pg version is 9.5.9.
I think it is related to the length of the view definition - try this view definition: https://gist.github.com/qwesda/402c405234c6b3d75d6cbc5fb26229e3

The `TAB` issues only happens with `MATERIALIZED` views ...

**Comment by qwesda** [comment]
The vanishing text is also worse with the `MATERIALIZED VIEW` ... sorry for the confusing description

**Comment by qwesda** [comment]
here is a gif of how it looks on my machine:

![out](https://user-images.githubusercontent.com/384993/33631561-3ae1d922-da0b-11e7-97fe-f4af7a8fb8f9.gif)

**Comment by jakob** [comment]
OK, thanks for the GIF. I've now been able to reproduce the vanishing text issue in a VM running macOS 10.13 beta. I'll see if I can somehow attach a debugger in the VM.

I've created a separate issue for the tab capture problem on 10.12 #465 

As for not being able to tab into a materialized view definition, that is by design. The view definition of a materialized view can not be changed, so the text field is read-only, and therefore it is skipped when tabbing.

**Comment by jakob** [comment]
@qwesda I think I've fixed this issue. If everything goes well, we're planning to release a new version of Postico this week. Could you let me know if one of the [recent builds](https://eggerapps.at/postico/builds/) (2097 or later) work for you?

**Comment by qwesda** [comment]
work fine in build 2108, thx!

The syntax highlighting still disappears on `mouse_down` when initially clicking in the field, but thats not so important.

**Comment by jakob** [comment]
Right, syntax highlighting does disappear while the mouse is down. It should reappear quickly after releasing the mouse. This is because the cocoa text system actually puts another view on top of the text field as soon as you start editing, so I need to reparse the text. Maybe I can find a way to pass the parse result so I don't need to reparse...

**Comment by qwesda** [comment]
It's only a very minor thing ... and it sounds like some ugly hacks might be required to make this happen.
