### ISSUE TITLE
View definition field "captures" tab

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#465]
It's not possible to use the tab key to leave the view definition field on macOS 10.12.6 (16G1036). It does work on High Sierra (tested on 10.13 Beta)

**Comment by qwesda** [comment]
Works in build 2108 ... but it's a bit confusing since non-editable fields look exactly as editable fields. If they would be greyed out it would be clear where the cursor will move next.
Also it would help users to see which fields are editable. I for one had no idea that materialised view definitions are not editable ...

Example: 
- column name/type/constrains for views
- type/constrains/definition for materialised views

**Comment by jakob** [comment]
I finally tracked this down... the problem wasn't related to macOS version, it was caused by the tabs vs. spaces preference.

**Comment by jakob** [comment]
Fixed in Postico 1.3.3
