### ISSUE TITLE
Let <tab> cycle through autocomplete options

### ISSUE THREAD

**Issue by iovis9** [jakob/Postico#477]
Congrats on the new feature!

I like how hitting `<tab>` opens the autocomplete window but muscle memory makes me keep hitting it to cycle through the results (with the actual text being changed to the completion selected).

Here's an example:
![example](https://user-images.githubusercontent.com/6660202/34255307-651bfc44-e650-11e7-8be9-783c678a86bf.gif)

**Comment by jakob** [comment]
We're aware that pgcli does it differently, but we've decided to make it work more like psql / bash (or readline in general), since that is what we assume that most people are familiar with.

(In addition to readline-ish tab completion, you can cycle through completions with the arrow keys, and confirm with return.)

I'm sorry that this isn't what you expect, but since there are many different implementations of tab completion out there, we had to pick one.

**Comment by iovis9** [comment]
Sure, it was just a suggestion! :)
