### ISSUE TITLE
Add a preference to disable auto-complete when typing a period

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#478]
Users have complained about the new auto-complete feature, so we should add a preference to turn it off.

**Comment by jacob-israel-turner** [comment]
To add to this, the UI often freezes up when I'm trying to view the `information_schema`.  I get this:
<img width="845" alt="screen shot 2017-12-22 at 9 17 00 am" src="https://user-images.githubusercontent.com/8698364/34304882-ee1875b0-e6f8-11e7-9754-1fed455e718f.png">
Sometimes it freezes during that fetch, sometimes it doesn't.  Would be nice to disable always, or even on a database- or schema-level.

**Comment by troylelandshields** [comment]
Yes unfortunately Postico is border-line unusable for me at the moment and I think it might be because of auto-complete. The database I'm connecting to has thousands of schemas that each have a dozen or so tables, so this might be why. In my case I just need the ability to disable the auto-complete entirely.

**Comment by jakob** [comment]
We shouldn't have shipped autocomplete without a way to turn it off -- sorry about that. While we are working on a way to disable it, you can use Postico 1.2.4 which does not have autocomplete:
https://eggerapps.at/postico/legacy.html

**Comment by jakob** [comment]
I've added a preference to disable autocomplete after typing a period in build 2235.

You can download build 2235 from here:
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-2235.zip
