### ISSUE TITLE
Copy/paste b/w tables with same structure fails if diff. order of columns

### ISSUE THREAD

**Issue by DaleStanbrough** [jakob/Postico#484]
Two separate databases with the same set of tables.

The columns had been reordered on one table.

Copy/paste from the same table from one db to the other db doesn't respect the column names and simply pastes columns in sequential order.

e.g. 
db1 table x
Columns A, B, C

db2 table x
Columns A, C, B

paste from db1::x to db2::x results in A, B, C values in columns A, C, B.

Postico version:  
1.3.1

PostgreSQL version:  
PostgreSQL 9.6.6

**Comment by jakob** [comment]
This behaviour is not a bug.

Matching column names would usually be what the user wants, but it wouldn't work in all cases.

In many cases, only some of the column names match, or the copied data may not have column names at all. What should we do in that case? For example, it would be confusing if Postico behaves differently just because one of the tables has one column with a different name, or extra columns, etc.

For this reason, I've decided to always paste values in the order they were copied. This is not always the most convenient, but it is predictable. It's also quite powerful, especially when copy/pasting data from other apps (like Excel, or from Safari)

I'm sorry if this is an inconvenience to you, but making sure that Postico's behavior is predictable is very important.
