### ISSUE TITLE
Enable users to disable Autocomplete

### ISSUE THREAD

**Issue by rowright** [jakob/Postico#487]
## What did you do?

I started typing a query over a slow connection on a heavily locked database and the autocomplete "Fetching database tables, functions, search path..." started running and takes a few minutes to complete. I to be able to execute queries in the SQL Query window without waiting for another query to finish. I tried to disable this functionality and found no preference or per server connection.

## What did you expect to happen?

The ability to enable or disable this feature either per connection/server or across the entire application.

## What software versions are you using?

Postico version:  
Version 1.3.1 (2153)

macOS version:  
10.13.1 (17B1003)

**Comment by jakob** [comment]
The problem is that Postico automatically triggers autocomplete as soon as you type a period. This issue is already tracked in #478.

We're about to release a new version of Postico that has a preference to disable autocomplete when typing a period. We'd love to hear your feedback on the newest build 2283 which you can download here: https://eggerapps.at/postico/builds/

It might also be useful to know that you can always cancel the currently running query with the shortcut Cmd-.

**Comment by rowright** [comment]
Awesome! Sorry - I should have searched a bit better in the issues. I'll close this!
