### ISSUE TITLE
How to get autosave queries when database is no more

### ISSUE THREAD

**Issue by Znarkus** [jakob/Postico#497]
## What did you do?

- Created a new database, deleted the old instance (database upgrade).

## What did you expect to happen?

- Want to copy the autosaved queries from the SQL Query view to the new connection window.

## What actually happened?

- Since it cannot connect to the now deleted database, (it seems) I cannot get to the autosaved SQL queries.

## What software versions are you using?

Postico version:  
1.3.2

---

If possible to get the queries out, it would be nice, even if it's a hacky way :)

**Comment by jakob** [comment]
Postico 1.3.2 stores autosave queries as text files in the Application Support directory:

`~/Library/Containers/at.eggerapps.Postico/Data/Library/Application Support/Postico/Autosave Queries`

If you've not yet opened the db with 1.3.2, the query might still be saved in the favorites database. If you still have the connection favorite, here's a trick to get the autosave queries:

1) Download Postgres.app and start it
2) Create a database with the same name as the one where you want to recover queries from
3) Then change the connection details of the favorite to connect to localhost (Postgres.app) instead

Postico autosaves queries per favorite and per database, that's why you need to make sure that the database you connect to has the same name.

**Comment by Znarkus** [comment]
Ah, found them! Thank you so much
