### ISSUE TITLE
Possibility to rename the Tabs

### ISSUE THREAD

**Issue by mariovol** [jakob/Postico#507]
You can use this template for reporting bugs.
Feel free to remove parts that are not relevant, or just write something free-form if you prefer.

## What did you do?

On Postico launch after connecting to the Server i see the last query i ran and when hitting CMD+t it opens the last queries i have had opened (very smart and clever).

## What did you expect to happen?

is it possible to rename the tab title instead of having: SQL Query - Server -DBSchema ??
same thing happens when loading a query, Postico is not working straight on the .sql file is it possible to do so?

## What software versions are you using?

Postico version:  
Version 1.3.2 (2318)

macOS version:  
10.12.6

Thanks a Lot

**Comment by jakob** [comment]
Yes, both of these suggestions are things we are working on.

But it requires some bigger changes to the user interface, so it's not something that we can ship in a minor update. It's also something I've been working on for quite some time (see for example https://github.com/jakob/Postico/issues/18) but it's not so easy to get it to work right.

I'm going to close this issue since there are already a number of similar issues open.

Thanks a lot for the suggestion!

**Comment by mariovol** [comment]
Thanks a lot for fastest answer ever and for the amazing job you are doing!
Take me in consideration for any beta testing :)
