### ISSUE TITLE
Opening details view crashes Postico

### ISSUE THREAD

**Issue by hunterboerner** [jakob/Postico#54]
I'm on 0.26 and opening the details view crashes Positco (CPU goes to 100% for a couple of minutes before OS X then I get a popup saying it crashed). It only happens when the details pane is smaller than a certain size (200px-ish) on a specific row (csv in gist). When I tried to open the csv in TextEdit, it crashed as well.

The row: https://gist.github.com/hunterboerner/1ab03612d5bd4d39e31e

**Comment by jakob** [comment]
Thanks for reporting this issue. Considering that it occurs in Postico and TextEdit, it could be a problem with Cocoa's text layout or rendering. Looking at the file, I would guess that the escape characters in the string might have something to do with it.

Unfortunately, I can't reproduce the issue. Displaying your file works fine on my computer, both in Postico and in TextEdit. I tried it on OS X 10.10.4 and 10.11. What version of OS X are you on?

Just a wild guess: I could imagine that the issue is related to a font that you have installed on your system. When OS X wants to draw a character that is not contained in the current font (like those escape characters), it tries to use a font that does. Maybe you have a font that has an escape character, and that font causes the crash?

Anyway, to debug this issue it would be invaluable if you could send me the crash logs. You can find them in the directory `~/Library/Logs/DiagnosticReports`. It would be really nice if you could send me the crash logs for both Postico and TextEdit. You can send me the crash logs via email to jakob@eggerapps.at

**Comment by hunterboerner** [comment]
Sent an email to you.

**Comment by jakob** [comment]
Looking through the backtrace you sent me, I see that Postico is stuck somewhere deep inside Cocoa's text layout framework. Unfortunately I don't think there is anything I can do to fix this, except file a bug with Apple if I find a way to reproduce it.

I also see that the bug happened on OS X 10.10.3. It's possible that Apple has fixed this issue in the mean time. Did the bug ever occur again?

(I'd like to apologise for the late response; I'm just looking through old issues, and I found out I have never written back to you)

**Comment by hunterboerner** [comment]
Tried on El Capitan and I still get this.

**Comment by jakob** [comment]
So does the CSV from the Gist crash TextEdit on your machine? It works fine on my machine.

Did you add any fonts to your system? Since the bug occurs during text rendering, this might be important.

**Comment by hunterboerner** [comment]
Yes it does. How did you download the csv? (wget-ing it and opening in text edit crashed it for me). I've installed some fonts. Mostly Google Fonts/Adobe TypeKit fonts.

**Comment by jakob** [comment]
I downloaded the gist by option-clicking on the "RAW" button; but downlaoding with curl I get the same result (ie. no crash on my machine)

Could you try removing all non-standard fonts on your system (Font Book has a command named "Restore Standard Fonts…" in the File menu), then restart your Mac and see if TextEdit still crashes when opening the file. (Don't worry, Font Book will not delete your custom fonts, it will just put them in a different folder).

Then we know if the problem is related to a font or something else. If it works with all user fonts disabled, use a binary search to find the problematic font (ie. install half of the user fonts again. If it crashes, remove half of the fonts you installed; otherwise install half of the remaining fonts, and repeat...)

Since this is likely a bug in OS X, not in Postico, it would be helpful if you'd report this bug to Apple (bugreport.apple.com).

**Comment by hunterboerner** [comment]
I fixed it! I had this setting set to true because of a dotfiles script I had inherited. This fixed it: `defaults write NSGlobalDomain NSTextShowsControlCharacters -bool false`

**Comment by jakob** [comment]
Thanks for following up on this. I've now been able to reproduce this issue, and reported it to Apple.
