### ISSUE TITLE
Feature request: Execute backups created by pg_dump

### ISSUE THREAD

**Issue by tomholub** [jakob/Postico#542]
I tried the "Load Query..." button, but it says:

> The file ... couldn't be opened using text encoding Unicode UTF-8

It's a binary dump file that I'd like to run.

**Comment by jakob** [comment]
Thanks for the suggestion! However, adding support for backup / restore is not something that's on our roadmap. It's very difficult to get right, and disastrous if you make a mistake.

pg_dump is a great tool, but it's written in a way that makes it very hard to include in other apps. My recommendation is to use pg_dump directly for backup / restore purposes.

**Comment by tomholub** [comment]
Thanks for the speedy response.

**Comment by harrislapiroff** [comment]
I'm surprised and bummed to read this conversation. Being able to import and export dumps is something I want to do fairly regularly with my dev databases, and even just a GUI wrapper around `pg_dump` would improve my workflow enormously.

Are there any tickets on Postgres itself that I could encourage along to improve `pg_dump` in this way?

Very happy Postico customer otherwise! Thanks for your hard work.

**Comment by jakob** [comment]
@harrislapiroff 
There's this thread on the hackers list that I started in 2016: https://www.postgresql.org/message-id/82EFF560-2A09-4C3D-81CC-A2A5EC438CE5@eggerapps.at

Since then, I haven't followed the issue closely. I've decided that backup / restore isn't really something that I can make better, and I decided to focus on other areas.

 pg_dump is very good, and I don't really see the big advantage of wrapping it in a GUI. It would just add a lot of trouble (eg. which version of pg_dump should Postico include?).

pdAdmin has a GUI for pg_dump, if you really want a GUI, but I think it is confusing and using pg_dump from the command line is easier.

**Comment by harrislapiroff** [comment]
I think the argument for wrapping `pg_dump` in a GUI is the same argument for most of Postico's features. As far as I'm aware anything I can do in Postico I could also do in a shell, but I like to do it in Postico because discoverability is easier with a UI, I don't have to remember the details of what to type or learn a tool or command or recall my database creds for one-off tasks. I don't even have `pg_dump` on my dev machine (presumably because all of my dbs are in docker containers and I don't have postgres installed on the host) so that's one of several hurdles that I have to jump through to get it working. I know that I can figure out how to do it (I usually have to look up the commands to produce and import dumps) but it'd be nice to be able to do it in a click.

Maybe it's just that I came from Sequel Pro where I _did_ do a lot of exporting and importing of databases from the GUI (to create a backup of a dev database before running a migration, for example) and that's a part of my workflow that I missed after I transitioned to Postgres.

Anyway, I don't want to make my case too strongly. It's a minor inconvenience in what's otherwise an excellent tool and your points about the potential pitfalls of tackling backup/restore are taken. I know you have many priorities to balance, but I wanted to at least make my case in the event that you consider it sometime in the future.

**Comment by jakob** [comment]
Hm. I kinda assumed that most people would have pg_dump installed locally, but with Docker, and all the hosted services like Redshift / RDS / etc, it makes sense that people would not have PostgreSQL installed locally. So it would be convenient if Postico was a one-stop-shop for all your PostgreSQL needs.

But for now, that's not where we're going. Postico focusses more on the "working with data" bits, and not so much on the "adminstrating your database" stuff. (Another important feature in that area that we're missing would be user and permission management.)

There are a lot of GUIs that try to do everything, and they do a mediocre job at everything. I'd rather have Postico do fewer things, but do them really well.

On the command line, there are lots of small, independent tools that do one job. For PostgreSQL we have psql for queries, pg_dump for backups, pgbench for speed tests, pg_upgrade for upgrading to a newer version of PostgreSQL, etc. I kinda wish it was like that on the GUI side too.

Postico could be the tool you use for exploring the database, and some other tool would be used for backup / restore, etc. We could have different tools that complement one another, rather than all database GUIs competing with eachother...
