### ISSUE TITLE
Dark mode support planned?

### ISSUE THREAD

**Issue by andreas-bergstrom** [jakob/Postico#557]
I am considering buying Postico but one big deal-breaker for me if you plan to adopt the dark mode in Mojave or not?

**Comment by jakob** [comment]
We've started working on it a bit, but it's a lot of work. We have a lot of custom drawing code in Postico, and it'll take a bit of effort to make everything compatible with dark mode. So I can't make any promises if and when we'll support dark mode. If it's a deal breaker, please wait until the feature is available before buying a copy. Please don't buy a license with the expectation that we will implement a specific feature in the future.

I'm closing this issue, since we're already tracking a dark mode feature request in #164.
