### ISSUE TITLE
CSV Import: Unexpected end of file

### ISSUE THREAD

**Issue by keithamoss** [jakob/Postico#573]
You can use this template for reporting bugs.
Feel free to remove parts that are not relevant, or just write something free-form if you prefer.

## What did you do?

Tried to import [this CSV file](https://gist.github.com/keithamoss/f2a3c0813f80f8e3a7fdb198725a8968) using the following settings:

![screen shot 2018-07-14 at 17 40 46](https://user-images.githubusercontent.com/1672960/42723277-a0d7688e-878d-11e8-8497-aa2cc71f6efa.png)

## What did you expect to happen?

The table to be loaded with 7477 records.

[Table definition](https://gist.github.com/keithamoss/ca466dc05e76d5bce47c0e335fed0821)

## What actually happened?

Received an error:

```
**Import failed**

Unexpected end of file on row 102255 column 305
No changes were made to the database
```

## What software versions are you using?

Postico version: 1.4.2 (2845)

macOS version: 10.13.5

PostgreSQL version: PostgreSQL 9.5.2 on x86_64-apple-darwin14.5.0, compiled by Apple LLVM version 7.0.0 (clang-700.1.76), 64-bit

**Comment by jakob** [comment]
Thanks for the test file!

The problem is in line 3528 -- there's a double quote that is not correctly escaped. Replace `One 6" step` with `One 6"" step` and the import should work!

We should try to make Postico show a better error message -- this message is not very helpful. (and the line number is totally off)

I've also made a smaller version of the test file for testing.

[573_minimal_test_case.csv.zip](https://github.com/jakob/Postico/files/2199412/573_minimal_test_case.csv.zip)

**Comment by keithamoss** [comment]
Thanks for taking a look!

Even an error message with just an accurate line number would be fine from my POV - it would have been enough to point me to the right place to fix the issue by hand.

Out of interest, I ended up getting it imported in Postico through the `copy from Excel -> paste into Postico` method. Had no issues with the unescaped `"` there.
