### ISSUE TITLE
What happened to side-scroll? 

### ISSUE THREAD

**Issue by abeburnett** [jakob/Postico#614]
Hi there,

I've been using Postico for awhile now, and I swear there's always been a side-scroll bar at the bottom of the window for scrolling sideways on wide tables. Now it seems that that scroll bar has disappeared. At least I don't see it. The only way for me to go sideways now is to select a row and drag to the left or right--which is not ideal.

I'm on the macOS 10.14, Macbook Pro Retina 15". Please advise!

**Comment by jakob** [comment]
If you use Apple input devices, macOS by default only shows scroll bars while scrolling (either using the two-finger swipe gesture on the trackpad, or by swiping with a single finger on the magic mouse).

If you use a third party mouse that only has a scroll wheel, by macOS should show scroll bars always (since you need them to  scroll sideways)

Are you using a third party mouse?

You can change that behavior in system preferences -> General -> Show scroll bars: Automatic / While Scrolling / Always.

Does that help?

**Comment by abeburnett** [comment]
Ah, PERFECT. Following your instructions I went to Preferences > General > and selected "Always" show scroll bars. This gives me the behavior I want. Thanks for point that out so quickly!
