### ISSUE TITLE
Pretty printing json column value inserts backslash in front of forward slash

### ISSUE THREAD

**Issue by cwhatley** [jakob/Postico#620]
## What did you do?

- Pick a row with some jsonb column value containing a forward slash "/"
- Open detail sidebar
- Choose pretty print json from the jsonb column

## What did you expect to happen?

- I expected to see reformatted json with string value contents unchanged

## What actually happened?

- All `/` in strings were replaced with `\/`

E.g., 

`{"a": "/x/y/z"}`

becomes:

```
{
  "a" : "\/x\/y\/z",
}
```

## What software versions are you using?

Postico version:  
1.5/4042

macOS version:  
10.14.3 Beta (18D21c)

PostgreSQL version:  
PostgreSQL 9.4.19 on x86_64-apple-darwin17.7.0, compiled by Apple LLVM version 9.1.0 (clang-902.0.39.2), 64-bit
PostgreSQL 10.3 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.3 20140911 (Red Hat 4.8.3-9), 64-bit

**Comment by martinjankoehler** [comment]
Hey @cwhatley  ,

we have fixed this issue and added some improvements regarding Postico JSON,
summarized in this issue:
https://github.com/jakob/Postico/issues/570#issuecomment-845312674

Any feedback or issues discovered are highly appreciated!

Best regards,
Martin

**Comment by martinjankoehler** [comment]
Thanks for your report, @cwhatley !

This issue (_ Pretty printing json column value inserts backslash in front of forward slash_)
is now fixed in the latest 2.0 beta and today's release 1.5.18 [(download)](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-1.5.18.zip).

Closing this one now, please feel free to open a new one should any issues occur.
