### ISSUE TITLE
Scrolling in results field stutters and spikes CPU usage

### ISSUE THREAD

**Issue by mwburke** [jakob/Postico#622]
## What did you do?

Scrolled within the results panel to view the data from a query with 33 columns and 100 rows.

Overall CPU usage was around 3% at the time.

## What did you expect to happen?

Before I updated to version 1.5 several minutes prior, scrolling in the results panel was smooth.

## What actually happened?

Now, when I scroll, the scrolling has a very low frames per second view update and does not scroll smoothly. Additionally, the CPU usage for Postico jumps from ~0.1% to up to 97.4% at the highest. 

## What software versions are you using?

Postico version:  
Version 1.5 (4042)

macOS version:  
Version 10.13.3 (17D102)

PostgreSQL version:  
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.5290

**Comment by jakob** [comment]
Hi!

Thanks for reporting this. I was able to confirm, there is a significant performance regression in scrolling. Profiling shows that the cause of the issue is extremely poor performance of named colors (they are used for dark mode support).

I was able to come up with a workaround for the issue -- we can resolve named colors when we first need them and cache the results. We only need to make sure to invalidate the colors correctly when the user switches between dark mode / light mode.

Can you try the following build and let me know if scrolling is snappy again?

[Postico 4087.zip](https://github.com/jakob/Postico/files/2703187/Postico.4087.zip)

**Comment by newhouse** [comment]
I had a similar issue, immediately noticing sluggishness in the "SQL Query" workspace...had to downgrade to 1.4.3.
When I go to the "SQL Query" workspace, I noticed some blinking and color changes to the text, then it stabilizes, but there's a lag in scrolling or even moving the cursor around within the same space.

This download you posted above made things a bit better, but still noticeably sluggish so I have downgraded again.

**Comment by mwburke** [comment]
Tried the new build. Scrolling seems smoother, but still seeing some significant CPU spikes when doing so.

**Comment by jakob** [comment]
@mwburke CPU spikes when scrolling are normal, drawing lots of text is CPU intensive.

We could enable "smooth scrolling", which might reduce CPU usage when scrolling slowly, but it would eat up a lot of memory (hundreds of megabytes, especially on large displays)

@newhouse I've only made improvements to the table view, but the same problem with the colors might also affect the text area. I'll see if I can fix it in a similar manner.

**Comment by Jurgem** [comment]
I still have a similar problem, and i had to downgrade to 1.4.4 (im using high sierra). 
The problem happen when i open the SQL Query editor (terminal) and then appear the "loading bar" of macOS. With the older version it work very well and fast... Maybe is that i have a lot of queries on my SQL Query editor? (like 20000 lines)

**Comment by jakob** [comment]
@newhouse @Jurgem I've opened a new issue for the SQL Text Editor performance issues you've reported. Can you try the build I posted in issue #629 and let me know if it resolves your problem?
