### ISSUE TITLE
License issue with Version 1.5.2 (4089)

### ISSUE THREAD

**Issue by cboothe** [jakob/Postico#624]
## What did you do?

- Updated due to crash fixes. When Postico runs it says it is running a free trial. Click on activate, with a license file it activates. Close and reopen the application and it once again says it is running a free trial.

## What did you expect to happen?

- In the past this was not an issue, or didn't even ask for a license file if already activated.

## What software versions are you using?

Postico version:  
Version 1.5.2 (4089)

macOS version:  
10.12.6

**Comment by jakob** [comment]
I've received a handful of similar reports via email, and I can't explain what is going on. It seems that for some reason, Postico doesn't see the license file (a copy of which is stored in the Application Support folder). I haven't touched any code related to license validation.

I have a few questions:

1. After you activate Postico, select "License Information" from the "Help" menu. Then click the "Show License File" button.
  - Is a license file displayed?
  - What's the full path of the license file that is displayed?

2. Do Connection Favorites disappear as well?

**Comment by cboothe** [comment]
Strange. I am using a pgCommander license but never had any issues before.

Doesn't seem to make a difference if I click the activate button and pick the file or if I copy the file over the Application icon and register that way.

1) After you activate Postico, select "License Information" from the "Help" menu. Then click the "Show License File" button.
Is a license file displayed?

Yes

What's the full path of the license file that is displayed?
"/Users/chris/Library/Containers/at.eggerapps.Postico/Data/Library/Application\ Support/Postico/license.postico-license"

2) Do Connection Favorites disappear as well?
No this seems to be unaffected.

Problem seems to be an extra backslash after "/Application\"

**Comment by jakob** [comment]
OK, so this all seems fine.

I've looked at the code a bit more, and it is possible that an exception is raised during application startup, before the license is read. Postico 1.5 added an automatic crash reporter to report exceptions, but apparently it doesn't work during application startup, because AppKit by default ignores exceptions during startup. 

Can you try the following:

1) Execute the following command to make sure Postico crashes on exceptions:

```bash
defaults write at.eggerapps.Postico NSApplicationCrashOnExceptions 1
```

Then try to start Postico again. If my assumption is correct, it should now fail to start.

Then go to ~/Library/Logs/DiagnosticReports and look for Postico crash reports. Please email them to postico@eggerapps.at as an attachment (if there is more than one, please email all of them!)

**Comment by cboothe** [comment]
@jakob Email sent with attachment. Postico did not start after flag was set.

**Comment by jakob** [comment]
Thanks for the crash report!

Could you check if this build works:

[postico-4090.zip](https://github.com/jakob/Postico/files/2716546/postico-4090.zip)

**Comment by cboothe** [comment]
Perfect! Works now.
