### ISSUE TITLE
Auto updater

### ISSUE THREAD

**Issue by tommoor** [jakob/Postico#625]
Love that Postico is regularly updated but the notifications to go to the website and download the update manually every time are a pain and I'm never quite confident that it's going to maintain my registration. 

## What did you expect to happen?

I'd expect to have an inbuilt auto updater like Sparkle, this is the only app I have purchased that doesn't keep itself up-to-date.

**Comment by voxpelli** [comment]
It is updated regularly nowadays and look fairly simple to implement: https://sparkle-project.org/documentation/

Especially easy for the web server side as its just a RSS-feed.

For me it works the way it is, but Sparkle would be a nice little extra 🙂

**Comment by dewey** [comment]
Came here to post exactly the same, manually downloading the new version every time and moving the app around is annoying and it's not as easy to see the change log like with a Sparkle-style update mechanism. Instead of looking forward to updates I dread them which isn't what it should be like.

**Comment by jakob** [comment]
This has come up before (#351, #49). Previously I didn't want to use Sparkle because it would allow breaking out of the sandbox. However, I've since realized that convenience is more important than the minor security risk of adopting Sparkle, so we will adopt Sparkle in a future version.

We're still evaluating the best way to implement this. Our goal is to support truly automatic updates (in the background, without any user interaction, automatically when you quit Postico). We need to make sure we do this right (eg. if you manually downgrade to an older version because of a bug, we should probably disable auto-update).

In any case, we're working on it, but it'll still take us some time to make it work. In the mean time, we'll keep releasing bugfix updates in the old, inconvenient way.

**Comment by dewey** [comment]
This is great news, thanks for the status update. FWIW I prefer to have the normal sparkle update screen I’m used to from almost every other App Store app I use instead of some fancy background updating. I can’t be the only one in the dev centric audience who doesn’t mind the additional click and knowing what changed on a high level.

At least then I know if something behaves differently that there was some update.

**Comment by danielcompton** [comment]
This would be my number one feature request for Postico. I appreciate all of the features that get added, but the frequent notifications about updating get annoying over time.

**Comment by martinjankoehler** [comment]
Hey there,

took us a while, but Postico 2 has an integrated auto updater feature based on Sparkle.

Please see the Postico 2 preview announcement #689 for details!

Best regards,
Martin
