### ISSUE TITLE
Have a way to change the role after connecting to the server

### ISSUE THREAD

**Issue by gajus** [jakob/Postico#626]
I have a user "gajus" and a NOLOGIN role "dba". The latter role is used to create/ manage all the schemas in the database. I wish to be able to login with "gajus" user, set role to "dba" and for Postico to use the latter role for all further queries, including schema changes.

This sounds like should be a common use case?

**Comment by jakob** [comment]
How do you do this now? Do you just log in as "gajus", and then use `SET ROLE` or `SET SESSION AUTHORIZATION` to change the user?

In any case, I'm not sure how common this specific use case is, but the more general problem of executing commands after connecting is probably somewhat common. That would be especially useful when Postico opens new connections (eg. after a lost connection, or if you open additional tabs).

**Comment by jakob** [comment]
Hi! I just wanted to let you know that we've added a way to automatically execute SQL after connecting in Postico 2. We call it "Startup Query". You can read about it in detail in issue #702.

I think that this should allow you to change the role after the connection is established. It's been some time since you suggested the feature, so I hope it's still useful for you.
