### ISSUE TITLE
Add option to remember choice of not connecting with encryption so no prompt appears every time on connect

### ISSUE THREAD

**Issue by nikitavoloboev** [jakob/Postico#637]
## What did you do?

- I try connect to a DB without encryption

## What did you expect to happen?

- I connect to it instantly without any prompts in my way

## What actually happened?

- I get a prompt:

![2019-02-14 at 11 25](https://user-images.githubusercontent.com/6391776/52780823-68c60880-304b-11e9-9627-946d9dec3d8e.png)

As I connect to this database very often and I know already that the connection is not secure I would like to have a setting in Postico for the DB that will remember the choice permanently. Currently Postico does this already for the current session of the app (as soon as I quit and open the app again and try connect, I will get same prompt).

**Comment by jakob** [comment]
Thanks for the suggestion!

However, this is by design. See this issue for detailed reasoning why there is no way to permanently disable the warning: https://github.com/jakob/Postico/issues/50#issuecomment-370369880

You can use a self-signed cert to avoid the warning.

If it's a local server, make sure to use either "localhost" or "127.0.01" or "::1" as the hostname, and the warning will also go away.
