### ISSUE TITLE
Export to .csv on external drive when local drive is nearly full

### ISSUE THREAD

**Issue by philshem** [jakob/Postico#638]
## What did you do?

Attempted to export a very large table (10 gb, 16M rows) as .csv to an external drive, using the "Export [table_name]..." context menu.

## What did you expect to happen?

A CSV file of the selected database table to be saved to my external drive.

## What actually happened?

My drive space on the local harddrive was limited and despite exporting to a mounted external drive, Postico froze consumed all available disk space on the local drive.

## What software versions are you using?

Postico version:   1.4.3

macOS version:  10.14.3

PostgreSQL version:  9.6

**Comment by philshem** [comment]
Unfortunately, I can't easily test, because I've since used pg_dump to export .sql (in this case, .sql was actually preferred to .csv).

But I could generate a table with something like this: https://stackoverflow.com/a/24841269/2327328

**Comment by jakob** [comment]
I've investigated the issue, and I think I know what's happening. Postico tries to fetch rows from the server as quickly as possible, and then writes them to disk in a separate thread. If the external drive can't write data as fast as the server delivers it, the RAM will fill up. If the data is bigger than available RAM, macOS will start writing data to swap, and fill up the boot volume.

We need to fix this by implementing some form of back-pressure, so that Postico stops reading while it is waiting for data to be written.

**Comment by jakob** [comment]
We've just released Postico 1.5.9, which now limits the amount of data in flight. It no longer reads data faster than it can write. This should fix disk space / memory related issues when exporting large tables (export should now also be a lot faster).

We've also improved cleanup code, so that Postico no longer leaves temp files behind when an export fails or is cancelled.

Thanks a lot for the bug report, it helped us to reproduce the issue, even if it took us a long time to finally fix it.
