### ISSUE TITLE
Scriptable startup and/or connections

### ISSUE THREAD

**Issue by lgomez** [jakob/Postico#640]
This isn't a bug. I tried looking for a possible answer or workaround in the issues but did not find one. My apologies if this is documented somewhere.

I deal with several databases and find myself switching connections often. Most of these are in different Google Cloud SQL which facilitates connecting through cloud_sql_proxy (a binary that I must run locally with some parameters for connecting).

Is there a way to have Postico either be started (with a particular connection configuration) from a shell script or somehow have it execute a shell command when attempting to connect to a particular config (which I suspect is not a feasible feature).

Thank you!

## What software versions are you using?

Postico version:  Version 1.5.5 (4311)

macOS version:  10.14.4 Beta (18E215a)

PostgreSQL version:  PostgreSQL 9.6.10 on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4, 64-bit

**Comment by jakob** [comment]
Yes, you can use connection URLs to open Postico from the command line: https://eggerapps.at/postico/docs/v1.5.5/postico-url-scheme.html

Connection URLs are quite powerful; you can use them to update favorites, and to automatically connect to favorites.

The UUID param currently doesn't work correctly when creating new favorites -- this will be fixed in 1.5.6
