### ISSUE TITLE
Feature Request: Custom delimiter for CSV import

### ISSUE THREAD

**Issue by landonreed** [jakob/Postico#646]
This is a feature request for the CSV import GUI. I have some tabular data that is delimited with single spaces ` `. Unfortunately, I don't think the current design of the GUI will allow me to import this data. It's possible that I could find/replace all of the spaces with a delimiter character that is supported, but it would be nice to be able to supply a custom delimiter to the import GUI (in addition to the predefined set).

Thanks!

**Comment by jakob** [comment]
We deliberately did not allow picking arbitrary delimiters because we wanted to keep it as easy to use as possible, and we wanted to see if we would get customer requests for other cases. We added the pipe as a separator character due to customer demand.

I'm not sure how popular spaces as separators are. Could you elaborate on the source of the file? Do you have reason to believe that space separated files are at least somewhat common?

Does importing the file work if you replace all spaces with tabs, pipes, or semicolons?

**Comment by landonreed** [comment]
Thanks for the response, @jakob. I'm not sure that space separated files are very (much less somewhat) common, it just happens to be the output from a somewhat homespun [web request logger in a Java application](https://github.com/opentripplanner/OpenTripPlanner/blob/f2b375364985b8dd83f791950d955e3ec5c9cb34/src/main/java/org/opentripplanner/api/resource/PlannerResource.java#L93-L123) I work with.

I've tried to replace the spaces with semicolons, but I'm running into some import issues that I think are due to issues with the input data (variable column counts on some lines). So, I would probably not rank this as a high priority on my use case alone, especially if restricting delimiters was a deliberate design decision in the first place.
