### ISSUE TITLE
Ask for password again if it was rejected by the server

### ISSUE THREAD

**Issue by jakob** [jakob/Postico#655]
## What did you do?

- Connect to a server with an incorrect password (either SSH password or PostgreSQL password)

## What did you expect to happen?

- Postico should show a dialog asking for the correct password

## What actually happened?

- Postico just shows an error message, and I need to edit connection settings to change the password

This is especially annoying when using temporary or one-time passwords, and when Postico opens a new connection (eg. when opening new windows/tabs or switching between databases on the same server)

## What software versions are you using?

Postico version:  1.5.6

macOS version:  any

PostgreSQL version: any

**Comment by abrom** [comment]
This is super frustrating. My work around at the moment is to create a bunch of duplicate connection favourites so I can connect with the new OTP. 

Same applies if there is a short network interruption. Postico tries to reconnect but fails because the OTP is no longer valid. 

Only solution to free up the connection favourite is to quit Postico and restart.

**Comment by jakob** [comment]
Postico 1.5.15 now recognizes the password error from the server and shows a dialog asking for the password.

**Comment by abrom** [comment]
Great, thanks @jakob 👍
