### ISSUE TITLE
Postico does not persist settings

### ISSUE THREAD

**Issue by pakohan** [jakob/Postico#671]
## What did you do?

When running Postico, settings are not persisted after closing the app.

## What did you expect to happen?

I expected the left sidebar to be still expanded, and all the other settings I've changed in the preferences pane still be there

## What actually happened?

The app was reset to the default settings. Even after deleting all the preferences and Postico itself it did not work. I've encountered this bug when I tried setting up pref sync via mackup. Since Postico overwrites the links mackup uses with the real files again, I've removed mackup syncing again. Since I've reseted Postico since then, I don't think it has to do with it. On another Mac, I'm not getting these errors

## What software versions are you using?

Postico version:  1.5.8

macOS version: 10.14.6

PostgreSQL version:  any

additional info:

```
Couldn't write value for key NSWindow Frame FavoritesWindow in CFPrefsPlistSource<0x6000017a5030> (Domain: at.eggerapps.Postico, User: kCFPreferencesCurrentUser, ByHost: No, Container: (null), Contents Need Refresh: No): setting preferences outside an application's container requires user-preference-write or file-write-data sandbox access
```

**Comment by jakob** [comment]
Postico uses the user defaults system to persist preferences. While settings are written to files in the preferences directory, they are also cached in memory by the macOS user defaults system, and recent versions of macOS really don't like it when you mess with preference files directly.

In addition to this, Postico is sandboxed, so it can't access any files outside of its container by default. The error message suggests that the user defaults system is trying to do that? I'm not sure why...

My recommendation would be to try the following:

1) Restart your computer. This should clear the preference cache, and fix any problems caused by a corrupted cache.

2) If that doesn't work, delete the Postico user defaults domain using the command `defaults delete at.eggerapps.Postico`.

3) If that still doesn't work, delete any preference files you can find for Postico, and restart your Mac again:
    - `~/Library/Preferences/at.eggerapps.Postico.plist`
    - `~/Library/Containers/at.eggerapps.Postico/Data/Library/Preferences/at.eggerapps.Postico.plist`

4) If that still doesn't work, delete the whole container `~/Library/Containers/at.eggerapps.Postico/`, restart your Mac, then relaunch Postico (this will delete your favorites as well, so maybe keep a backup of the folder just in case)

**Comment by pakohan** [comment]
Doing **all** of it at once worked. Although it told me that `defaults delete at.eggerapps.Postico` failed because it didn't know that domain. So the only thing I did different this time was restarting the Mac. I thought I don't need to do this in 2019 anymore :-/

**Comment by johnwpz** [comment]
I'm seeing a similar issue with Postico v2.1.2 on a new MacBook Air M4 (macOS Seqouia 15.4).

I tried:

1. `defaults delete at.eggerapps.Postico`
2. `rm -rf ~/Library/Containers/at.eggerapps.Postico/` (I had to enable full disk access for Terminal to get around the "Operation not permitted" errors)
3. Restart macOS

I also tried:

1. Booting into safe mode
2. Deleting and reinstalling Postico
3. Deleting/re-creating the library in settings

Initially I imported my server list. Do you think that had something to do with it?

Thanks in advance.
