### ISSUE TITLE
Odd copy/paste issue with Visual Code

### ISSUE THREAD

**Issue by wellsoliver** [jakob/Postico#677]
I use Visual Code a lot, and often paste queries into Postico. This started happening recently where Postico does not properly parse the pasted SQL: it yields weird errors like:

```
ERROR:  type " " does not exist
LINE 27:     on tablename.col = 'person'
                               ^
```

It also does not properly syntax highlight the pasted SQL, and does odd things where double clicking on a column name in a WHERE clause highlights multiple space-separated words, instead of the selected word.

I'm inclined to think it's something in Visual Code, as it seems to have started happening recently and Code is updated more frequently than Postico, but it's quite frustrating and I wanted to make you aware. I assume a lot of folks use both tools.

Postico 1.5.8 (4819), Visual Code 1.38.1 (commit b37e54c98e1a74ba89e03073e5a3761284e3ffb0). MacOS Mojave 10.14.6.

My SQL files in Code are saved as UTF-8 w/ LF end of line sequences.

**Comment by jakob** [comment]
Here's a new build that attempts to fix this issue:
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-5186.zip

The issue is already tracked in an old issue (#445). I've only been able to reproduce the issue recently, and judging by customer complaints it seems that VS Code has recently changed something since it now affects many people (I seemed like it was only a rare issue previously)

Please leave this issue open, even though it's a duplicate, since the other issue is a bit hard to find. We still need to do a bit of testing, but we hope to release Postico 1.5.9 with the fix soon.

**Comment by MerrickClark** [comment]
Running into this issue too. It seems like it's something on the Postico end but I didn't exhaustively test. I just copied a 'space' character from within VSCode & plugged that into a hex decoder yielding `\x20` & then same with 'space' character from a pasted-into-Postico-from-VSCode query & decoder indicated it was `\xC2\xA0`

**Comment by jakob** [comment]
@MerrickClark It's not a Postico issue, it's an issue with VS Code. The issue happens with every app that uses Cocoa text views configured as "rich text". This means that aside from Postico, a lot of other apps, including Apple's own Text Edit and Mail, are affected.

Unfortunately the VS Code devs don't think anything is wrong and apparently want all other apps to add workarounds for their problem (see issue https://github.com/microsoft/vscode/issues/80825). It's unfortunate that all these Electron apps completely disregard platform conventions and then expect everyone else to deal with it. 

Build 5186 adds a workaround for the issue, so please use that while we are still finishing Postico 1.5.9.
