### ISSUE TITLE
Millisecond granularity for execution time

### ISSUE THREAD

**Issue by yiweig** [jakob/Postico#685]
First off, I love Postico. It's my goto over anything (psql, JetBrains' built-in console, etc).

Would it be possible (is it possible already?) to get the execution time in the bottom right to display in milliseconds? Sometimes when I'm comparing queries it'd be nice to see more granular durations.

**Comment by jakob** [comment]
I think short queries already display durations in ms.

However, those times include network transfer time, so they aren't precise to the millisecond anyway. Showing milliseconds would probably be misleading.

The better way to time queries is to use EXPLAIN ANALYZE. Then the execution time is measured server side and is precise, because it does not include any delays incurred by the network.

**Comment by yiweig** [comment]
> I think short queries already display durations in ms.

Ah yes, you're right, I've been working with a bunch of long running queries recently so I missed this.

> However, those times include network transfer time, so they aren't precise to the millisecond anyway. Showing milliseconds would probably be misleading.

This is true, I hadn't considered network latency (been doing a lot of stuff locally). But totally makes sense.

Thanks for the quick reply, I'll close this out!
