### ISSUE TITLE
Postico 2: [pgFormatter] Make a decision about --function-case

### ISSUE THREAD

**Issue by frou** [jakob/Postico#712]
## What did you do?

- Used the `Format All SQL Statements` feature.
## What did you expect to happen?

- SQL function names to be formatted consistently.

## What actually happened?

- They aren't. e.g. this is the content of a query file after formatting:

```sql
SELECT
    SUM(bar)
FROM
    x;

SELECT
    sum(bar)
FROM
    y;

SELECT
    suM(bar)
FROM
    z;
```

I imagine this is because the default value of the `--function-case` flag of `pg_format` is too lax (compared to `--keyword-case` and `--type-case`):

```
    -f | --function-case N: Change the case of the reserved keyword. Default is
                            unchanged: 0. Values: 0=>unchanged, 1=>lowercase,
                            2=>uppercase, 3=>capitalize.

    -u | --keyword-case N : Change the case of the reserved keyword. Default is
                            uppercase: 2. Values: 0=>unchanged, 1=>lowercase,
                            2=>uppercase, 3=>capitalize.

    -U | --type-case N    : Change the case of the data type name. Default is
                            lowercase: 1. Values: 0=>unchanged, 1=>lowercase,
                            2=>uppercase, 3=>capitalize.
```

Please you folks make a decision about which non-zero value to use for `--function-case` 🙂 

## What software versions are you using?

Postico version:  2.0beta (6573)
macOS version:  10.15.5
PostgreSQL version:  12.3

**Comment by jakob** [comment]
The only argument that Postico passes to `pg_format` is `--spaces` or `--tabs`, according to preferences for the query editor.

We didn't change any of the other settings, assuming that @darold knows more about SQL formatting than we do. Maybe there's a reason why the default is "unchanged"

I did some testing with the online version of pg_format (http://sqlformat.darold.net), and it seems that `--function-case` only applies to PostgreSQL builtin functions (regardless of whether the function name is a keyword or not). It does not apply to user defined functions or functions from extensions (so PostGIS function names would be unaffected by the setting).

Since functions names in the PostgreSQL documentation are all lowercase, and the PostgreSQL server internally folds all unquoted identifiers to lowercase, it would make sense to use `--function-case 1` (lowercase) in my opinion, just like type names.

(There's also an argument to be made that `pg_format` arguments should be configurable, but we wanted to see how many people complain about the default settings before adding a preference that only very few people would change.)

**Comment by frou** [comment]
Thanks, that all sounds reasonable.

It's a shame pgFormatter doesn't have an official config file format, because then the Postico UI Preference could just be "point us to your custom config file".

**Comment by darold** [comment]
Well I guess that this is a way to ask for the feature :-)

**Comment by jakob** [comment]
Making the arguments that Postico passes to pg_format configurable isn't really difficult (it's just an array of strings), and adding a config file wouldn't really make it easier. The reason why I'm hesitant to add preferences is because every single preference makes Postico a bit harder to maintain and adds another way that something can go wrong.

@darold Since you replied, was there a specific reason why the default for `--function-case` is `0` rather than `1`?

(BTW, thanks a lot for making pg_format and releasing it under a permissive license, it's a really great tool.)

**Comment by darold** [comment]
Actually default function case is 0 because the first idea was to cover all functions, not just the built-in functions, so when started I have though that it was better to keep them unchanged. As it can just cover the built-in functions I agree that it should be the default but this will introduce a backward compatibility issue. This is the first time I have complain about that, I guess that the reason is that there is an option to change this behavior :-) I think you or @frou could open an issue about turning functions into lower case by default on pgFormatter github repository so that other can express their point of view.

However, I understand that a configuration file to change the formatting default is something that could save time and allow external program to let the user customize their formatting without need to edit a property. I will implement it.

**Comment by jakob** [comment]
Thanks for the explanation!

We changed the default arguments of pg_format to include `--function-case 1`.

Built-in PostgreSQL functions should now be lowercased, while other functions (such as PostGIS functions or user defined functions are left as is). I think that's a good compromise, since PostGIS functions have mixed case in the docs.

**Comment by frou** [comment]
@jakob Thank you for implementing.

And thank you @darold for engaging. Really my mention of a config file was an off-hand remark and I'm not advocating any specific changes to pgFormatter. Of course if there is to be a config file, there are general design subtleties like whether a config file is only used if explicitly pointed to using a command-line flag, or whether it implicitly searched for. And if it is implicitly searched for, is that only in a fixed location (e.g. `~/.pg_format`) or is every parent of the working directory where `pg_format` is run from searched recursively.

**Comment by darold** [comment]
No worry I have understood thing like that, chance was that @jakob include me in the topic otherwise it never reach my scope.

pgFormatter commit e7450fd adds support to configuration file. Auto-detected as `~/.pg_format` or `pg_format.conf` in the CGI mode. I will try to publish a new release next week.

**Comment by porsager** [comment]
@jakob Could postico make use of the settings in `~/.pg_format`?

**Comment by martinjankoehler** [comment]
@frou @darold @porsager 
We've been working on this pgFormatter integration issue.

Postico 2 now makes use of the settings in `~/.pg_format`,
this is now available using the built-in auto updater or manually at
https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-8974.dmg

Best regards,
Martin
