### ISSUE TITLE
Stuck getting configuration parameters

### ISSUE THREAD

**Issue by ibielopolskyi-godaddy** [jakob/Postico#729]
## What did you do?

Connecting to the remote database from favorites window

## What did you expect to happen?

Connection to database :)

## What actually happened?

Stuck at the "getting configuration parameters step"
Sometimes it unstucks in 5-10 minutes, and sometimes I need to restart Postico completely

## What software versions are you using?

Postico version:  
(select "About Postico" from the Postico menu)

macOS version:  10.15.6

PostgreSQL version:  1.5.14

**Comment by jakob** [comment]
The command that Postico executes when it shows that message is `SHOW ALL`. Usually that command should not take very long, unless you have a very slow network connection, or there is a problem with the network (eg. firewall).

What kind of server are you connecting to? Is it a normal PostgreSQL server, or are you connecting through a proxy or connection pooler? Do you know which version of PostgreSQL the server is running?

Can you connect to the server with `psql`? What happens when you execute `SHOW ALL` in psql?

**Comment by ibielopolskyi-godaddy** [comment]
Thank you for your prompt response.

> Do you know which version of PostgreSQL the server is running?
psql (11.8, server 11.7 (Debian 11.7-0+deb10u1))

> Is it a normal PostgreSQL server, or are you connecting through a proxy or connection pooler?
Direct connection

>Can you connect to the server with psql? What happens when you execute SHOW ALL in psql?
That's a nice lead, thanks. Indeed, connection with psql is just fine. However, when I execute SHOW ALL it hangs just like from within Postico.

Seems like it has nothing to do with Postico. Thank you.
