### ISSUE TITLE
connect server with sslmode false

### ISSUE THREAD

**Issue by hanbge** [jakob/Postico#741]
how to connect server with sslmode=false or sslmode=disable ?

**Comment by jakob** [comment]
Postico doesn't support disabling SSL.

If you connect to localhost, Postico uses sslmode=prefer.

Otherwise, Postico uses a custom sslmode where certificates are verified using the macOS security framework / keychain.

If the server does not support SSL, Postico shows a dialog asking if you would connect without encryption, falling back to sslmode=prefer.

If you are asking because of the Big Sur bug where macOS can not read certain certificates, please try using Postico 1.5.15, which we plan to release tomorrow. You can download it ahead of time here: https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-7378.zip

**Comment by jakob** [comment]
Postico 1.5.15 was just released. I'm closing this issue now.

If your problem isn't fixed by Postico 1.5.15, feel free to reopen this issue or open a new one.
