### ISSUE TITLE
Open Contents in a new Tab

### ISSUE THREAD

**Issue by jamesbeith** [jakob/Postico#747]
**Feature request**

When right clicking on a table in the sidebar, there is a menu item to "Open Contents".

Holding the Command key changes this option to "Open Contents in a new Window".

Would it be possible to add support for "Open Contents in a new Tab".

![Screenshot 2020-11-27 at 10 00 03](https://user-images.githubusercontent.com/456480/100418946-ad634c80-30d7-11eb-90f4-9840a9cbe697.png)

**Comment by martinjankoehler** [comment]
Hello @jamesbeith ,

we've been working on this feature.

If you are already using the Postico 2.0 beta, you can just use the "Check for Update" function to install the latest build.
Otherwise you can download a pre-release build here: https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-7901.dmg

Best regards,
Martin

**Comment by jamesbeith** [comment]
Thanks @martinjankoehler that's working perfectly, including preserving any Filters when opening in a new tab 👏🏼
