### ISSUE TITLE
Is there an option to make postico prompt for `database` if left empty

### ISSUE THREAD

**Issue by pramodc** [jakob/Postico#751]
I have a favorite connection and I would like to connect to different databases using that favorite. If I leave the database field blank, postico connects to the database same as the username. Is there an option override this default behavior? Is there an option to make postico prompt for the database name when connecting?

Thanks!

**Comment by jakob** [comment]
In Postico 1.5, there is the "show all databases" option in the favorite settings. Enabling this shows a list of databases after connecting. 

In Postico 2 Beta you can click the "show databases" button to show a list of databases on the server

**Comment by amfriedman** [comment]
Many of my database credentials contain a username that does *not* have a corresponding database name. I checked the option "Show All Databases". Still, I get the connection error: "connection to server at "myserver.net" failed: FATAL:  database "myusername" does not exist". How do I solve this? I would argue that the app should not try to be clever and assume any database name, for any reason.

**Comment by jakob** [comment]
My apologies, it seems I didn't read the question carefully and didn't actually answer the question. Let me try to explain why Postico behaves the way it does.

When connecting to PostgreSQL servers, you always have to connect to a specific database. Other database systems allow you to connect to a server first, and select a database afterwards. PostgreSQL can not do that. Each connection is with a specific database, and when you want to change database you have to open a new connection. There is no way around that, this is a limitation of the PostgreSQL architecture.

Postico automatically opens new connections when you switch databases. But for the initial connection, you need to provide a database name to connect to. If you don't know the name of a database on the server, you can't connect.

Postico uses libpq to connect to the server. When you don't provide a database name, libpq just tries to connect to a database with the same name as the user. Sometimes that works, sometimes it doesn't. But this default is not something I invented in Postico, this is the default behavior for libp, for psql, and for almost every other PostgreSQL client out there. Which is why Postico behaves the same. I really don't want Postico to behave differently from other PostgreSQL tools in that regard -- if a connection URL works with psql, it should also work with Postico.

I've gotten so used to this that I don't really question it any more, but I agree that it is a somewhat annoying feature of PostgreSQL. But considering how entrenched this feature is in the PostgreSQL community, I doubt it will ever change.

**Comment by amfriedman** [comment]
Thank you so much, I am very new to working with PostgreSQL and so I missed this crucial detail about their server architecture. It is definitely something that is out of your control!
