### ISSUE TITLE
Postico 2 Beta - Redshift - Completion fails due to missing comment column

### ISSUE THREAD

**Issue by sinok** [jakob/Postico#755]
## What did you do?

- Started writing a simple query and wanted to activate the completion 
- Pressed control+space

## What did you expect to happen?

- Showing the list of matching tables/schemas (postico v1.5.17 screenshot for reference)
![Postico 1 Screenshot](https://user-images.githubusercontent.com/4171441/110607488-882cb280-818b-11eb-90c5-279a987cc741.png)

## What actually happened?

- The completion popup showed empty besides an error message saying that the comment column is missing

![Postico 2 Screenshot](https://user-images.githubusercontent.com/4171441/110607659-b3af9d00-818b-11eb-8838-b70fc46ee963.png)

## What software versions are you using?

Postico version:  
Version 2.0beta (7800)

macOS version:  
11.2.2 (20D80)
PostgreSQL version:  
PostgreSQL 8.0.2 on i686-pc-linux-gnu, compiled by GCC gcc (GCC) 3.4.2 20041017 (Red Hat 3.4.2-6.fc3), Redshift 1.0.24265

**Comment by martinjankoehler** [comment]
Hello @sinok,
thanks for reporting!
I've tried to reproduce this with Build 7800 and Redshift 1.0.24265, so far it works on my side:
![Bildschirmfoto 2021-03-10 um 11 37 26](https://user-images.githubusercontent.com/29398377/110616592-fe81e280-8194-11eb-9fbb-a76647114d17.jpg)
Also, if a table has a comment, this is shown accordingly:
![Bildschirmfoto 2021-03-10 um 11 38 49](https://user-images.githubusercontent.com/29398377/110616742-30934480-8195-11eb-8e22-3c9304b834f3.jpg)
Is there anything "special" about your Redshift installation which could help me in order to reproduce this issue?
Best regards,
Martin

**Comment by sinok** [comment]
Hi @martinjankoehler 
It is definitely related to this Redshift Cluster. Tried with another one and it worked properly.

The versions are the same. The account is the same.
So I'm not really sure where I should be investigating.

What would be the metadata queries that are failing in order to get this information?

**Comment by martinjankoehler** [comment]
Hi @sinok 

reviewing all the code paths at the moment.
It could be caused by a difference in `pg_catalog.svv_external_tables`, is this the case on your side?

Best regards,
Martin

**Comment by sinok** [comment]
Yes, it is the case. ;)

**Comment by martinjankoehler** [comment]
Hello @sinok,

please try the build https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-7817.dmg
Let's see if it also resolves the issue on your side.

Best regards,
Martin

**Comment by sinok** [comment]
Hi @martinjankoehler 

Just installed the build, the issue is gone
Thanks a lot,

Best regards,
Sébastien
