### ISSUE TITLE
Wrong query scope execution when semicolon is set after open parenthesis ‘(‘

### ISSUE THREAD

**Issue by Julien0002** [jakob/Postico#756]
## What did you do?

- add semicolon to execute part of the query

## What did you expect to happen?

- the query part above the semi-column is no longer taking in the execution query scope

## What actually happened?
- the scope in consideration do not change
![image](https://user-images.githubusercontent.com/17622527/110620963-f7a99e80-8199-11eb-904d-96c80a40c770.png)

## What software versions are you using?
Postico version:  
Version 2.0beta (7800)

macOS version:  
10.15.7 (19H524)

PostgreSQL version:  
all

**Comment by jakob** [comment]
PostgreSQL statements can contain semicolons within parenthesis -- this is required for the CREATE RULE command.

That's why Postico behaves this way.

If you only want to execute part of a query you can do the following:

- comment parts of the query with command-slash

- select the part that you want to execute, then click "execute selection"
