### ISSUE TITLE
SQL line comments do affect next line

### ISSUE THREAD

**Issue by cansik** [jakob/Postico#76]
![image](https://cloud.githubusercontent.com/assets/5220162/10040393/746abf42-61db-11e5-893c-bc9e5eadbeac.png)

Why do line comments affect the line under the comment? It works if I put a space between the comment line and the sql query, but this is a bit strange. In every SQL editor I use, line comments do only affect the own line.

**Comment by jakob** [comment]
This looks like a bug. Did you paste that code from somewhere or type it directly? It would also help if you could save the problematic query and email it to jakob@eggerapps.at -- but I understand the full query might be confidential.

Can you try the latest build I linked in issue #11 (I've made a few changes to the parsing code?

Anyway, thanks for reporting this issue; I'll look at it in more detail tomorrow.

**Comment by jakob** [comment]
I've looked at the text file you emailed me, and it seems that the query uses the unicode `LINE SEPARATOR` (U+2028) character instead of a standard `NEWLINE` (or `LINEFEED`). While Cocoa treats the line separator correctly, PostgreSQL treats it like a normal character. That's why the comments don't end.

For this reason, the syntax highlighting in Postico is correct; however the special character should probably be somehow highlighted or removed.

I'm closing this issue since it is the same underlying problem as #75
