### ISSUE TITLE
the default filter option for UUID columns should not be `contains`

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#765]
## What did you do?

-in the table view: right click on the column header of a uuid column and select filter

## What did you expect to happen?

- the filter bar being refilled with the column and the filter type `=`

## What actually happened?

- the filter type is set to `contains` and `=` is not even selectable
- you can only select `is exactly` which casts the column to text and thus ignores indices for the column (unless the index also casts the uuid to text)

## What software versions are you using?

Postico version:  
- tested on `Version 1.5.17 (8121) ` and `Version 2.0beta (8062)`

**Comment by martinjankoehler** [comment]
Thanks for your report, @qwesda  !
 (_default filter option for UUID columns should not be contains_)

This issue is now fixed in the latest 2.0 beta and today's release 1.5.18 [(download)](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-1.5.18.zip).

Closing this one now, please feel free to open a new one should any issues occur.

**Comment by qwesda** [comment]
thank you very much, it's working correctly in the new build!
