### ISSUE TITLE
Too many favorites, can't scroll to enter password

### ISSUE THREAD

**Issue by olivierlacan** [jakob/Postico#766]
![image](https://user-images.githubusercontent.com/65950/119739814-ce231980-be50-11eb-9638-d75f792246c8.png)

## What did you do?

Tried to connect to favorite (number 13, unlucky) and the list won't scroll to allow me to enter a password.

## What did you expect to happen?

Being able to scroll to enter the password in the prompt.

## What actually happened?

Had to quit the app and delete favorites to be able to access the password prompt.

## What software versions are you using?

Postico version:  1.5.17

macOS version:  
10.15.7 

PostgreSQL version:  
N/A

**Comment by jakob** [comment]
Oh, the dialog extends past the bottom of the window. This is not ideal.

As a workaround, you can just move the window further up away from the bottom of the screen.

We should probably fix this. (It's already fixed on macOS Big Sur, where these modal dialogs are now placed in the center of the window.

**Comment by martinjankoehler** [comment]
Thanks for your report, @olivierlacan  !
 (_Too many favorites, can't scroll to enter password_)

This issue is now fixed in the latest 2.0 beta and today's release 1.5.18 [(download)](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-1.5.18.zip).

Closing this one now, please feel free to open a new one should any issues occur.
