### ISSUE TITLE
Postico 2 - Copy INSERT Statement doesn't include JSON columns

### ISSUE THREAD

**Issue by ramblingenzyme** [jakob/Postico#767]
You can use this template for reporting bugs.
Feel free to remove parts that are not relevant, or just write something free-form if you prefer.

## What did you do?

- I clicked on Copy INSERT Statement on a row
## What did you expect to happen?

- I expected to paste an SQL statement with JSON data

## What actually happened?

- The JSON column value is `E'NULL'`

## What software versions are you using?

Postico version:  Version 2.0beta (8127)

macOS version:  11.2.3 (20D91)

PostgreSQL version:  PostgreSQL 12.4 on x86_64-pc-linux-gnu, compiled by x86_64-pc-linux-gnu-gcc (GCC) 7.4.0, 64-bit

**Comment by martinjankoehler** [comment]
Thanks for your report, @ramblingenzyme!

This issue (_Copy INSERT Statement doesn't include JSON columns_)
is now fixed in the latest 2.0 beta and today's release 1.5.18 [(download)](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-1.5.18.zip).

Closing this one now, please feel free to open a new one should any issues occur.
