### ISSUE TITLE
SQL query result money columns sorted lexicographically instead of numerically

### ISSUE THREAD

**Issue by RyanDurk** [jakob/Postico#768]
The result set returned in the query window is correctly sorted when run. However, the GUI apparently treats money values as strings (probably because of the '$' sign), and accordingly sorts the values as strings.

## What did you do?

First, run a query:
SELECT unnest('{10, 2, 30}'::money[])
ORDER BY 1

Then, click the column header a few times to see the sorting results. 

## What did you expect to happen?

Clicking the column header should sort money values numerically.

## What actually happened?

The money values are sorted lexicographically.

## What software versions are you using?

Postico version:  
1.5.17

macOS version:  
11.2.3

PostgreSQL version:  
13.2

**Comment by martinjankoehler** [comment]
Thanks for your report, @RyanDurk !
 (_ SQL query result money columns sorted lexicographically instead of numerically_)

It is now fixed in the latest 2.0 beta and today's release 1.5.18 [(download)](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-1.5.18.zip).

Closing this one now, please feel free to open a new one should any issues occur.
