### ISSUE TITLE
Pretty print JSON by default?

### ISSUE THREAD

**Issue by xarg** [jakob/Postico#82]
More often then not I want to read the JSON inside the fields. And I'm not storing indentation to save space. Right now there is the Pretty Print JSON option, but I have to click it for every row/field and it changes the field which is rarely what I actually want to do. 

One negative aspect of this could be: If the JSON field is pretty printed by default and it's not what you have in the DB it could create confusion. Since only whitespace changes, I wouldn't expect much confusion though. I would love an option to show JSON pretty-printed by default.

**Comment by jakob** [comment]
It would probably make sense for the new `jsonb` data type, since that type doesn't store any formatting information anyway. The normal `json` type is basically just a text field, so I don't want to mess with formatting there; especially since formatting might hide issues like duplicate keys.

I'll look into it; long term I'd love to implement a full graphical JSON editor.

**Comment by visini** [comment]
I second this! We use jsonb extensively and it'd be a great feature to pretty-print all jsonb data

**Comment by vincent-dm** [comment]
I would also appreciate this option very much!

**Comment by pauldoerwald** [comment]
I would love a feature like this. I emailed Jakob about it yesterday and he referred me to this ticket, so I'm recording my thoughts here.

Rather than hovering over the cell to reveal formatted JSON content, I would rather be able to double-click the cell, or click on a tiny link inside the cell, to reveal a large enough overlay with the pretty JSON inside of it. I suppose the same mechanism could be used for other large or complex types (text, hstore?).

I think a JSON editor would be overkill. Neat, but probably unnecessary.

**Comment by dazzaji** [comment]
FWIW, also looking into using Postico for deeper work with JSON.  Would be great to see some more support for it.

**Comment by mviau123** [comment]
Also want deeper JSONB viewer / editor right inside Postico, starting to use it about everywhere, so like "single field column" so a good JSONB view / editor in Postico would be Huge for me, thanks.

**Comment by simonlast** [comment]
+1 on this

**Comment by aconran** [comment]
Would love to see this

**Comment by mviau123** [comment]
+2!   Having to copy paste to Sublime to view fields.  using PG as a document store hybrid system with jsonb field is imho up and growing as a "best of both worlds" solution.

**Comment by cwhatley** [comment]
I think the editor idea is great, but the core feature I'm interested in here is an option to have a readable JSON field that is pretty-printed by default.

**Comment by venkatd** [comment]
While more full featured support would be nice, a quick solution with a huge impact on my workflow would be: pretty printing JSON columns and allowing me to view that in a new window.

**Comment by schmitzdenis** [comment]
+1!

**Comment by sheharyarn** [comment]
Want to bump this again. Would love the pretty-print-by-default option since it'll make my life so much easier!

**Comment by sheharyarn** [comment]
Back here after 10 months, still requesting this. I believe it should be pretty easy to do and shouldn't require a lot of effort for a basic implementation. You could use something like postgres' built-in `jsonb_pretty` function internally.

https://til.hashrocket.com/posts/87ac2dcf6d-pretty-printing-jsonb-rows-in-postgresql

**Comment by visini** [comment]
I was so excited after I got a notification, but, after 4 years, we‘re still here. One can still hope! Thank you for your work @jakob

**Comment by jakob** [comment]
OK, so I tried just using the `jsonb_pretty` function for fields of type JSONB.

If you want to see what it looks like, you can download a build here: https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-5881.zip

While the result is obviously great for displaying JSON data in the sidebar, it's not-so-great when looking at the table view, because all you are going to see now is just some curly braces most of the time.

Look at the data column in the following screenshot:

<img width="1001" alt="Bildschirmfoto 2020-01-22 um 18 15 44" src="https://user-images.githubusercontent.com/198305/72916946-38024f00-3d43-11ea-923a-2d75ee849ddb.png">

Here's a screenshot from Postico 1.5.10 for comparison:

<img width="1054" alt="Bildschirmfoto 2020-01-22 um 18 17 36" src="https://user-images.githubusercontent.com/198305/72917080-7992fa00-3d43-11ea-88c5-b6f8d2b4771e.png">

I think the best solution would be if Postico showed the formatted data in the sidebar, and the unformatted data in the table view. Unfortunately this is not possible with the current architecture, since the data displayed in the sidebar and in the table view is always identical. So fixing this is not an easy change, and I still need to think about this issue for a bit.

**Comment by sheharyarn** [comment]
Thank you for looking into this again @jakob! Personally I would prefer this if I had to choose between the two but I understand this isn't ideal and might actually be disliked by other users. But still hoping you figure this out! 🤞

In the meantime I'll use the new build you uploaded 😄

**Comment by visini** [comment]
> If you want to see what it looks like, you can download a build here: https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-5881.zip
> 
> While the result is obviously great for displaying JSON data in the sidebar, it's not-so-great when looking at the table view, because all you are going to see now is just some curly braces most of the time.

While I agree with @sheharyarn it's not an ideal solution, I also prefer the `jsonb_pretty` approach. Thank you for your work @jakob, truly outstanding over the last years!

**Comment by martinjankoehler** [comment]
Hey folks,

we have been working on some improvements regarding Postico JSON,
summarized in this issue:
#570 (comment)

Any feedback or issues discovered are highly appreciated!

Best regards,
Martin

**Comment by martinjankoehler** [comment]
Postico 1.5.18 was released today [(download)](https://eggerapps-downloads.s3.eu-west-1.amazonaws.com/postico-1.5.18.zip) and contains some JSON fixes, including pretty-pretting of `jsonb` values.

**Comment by jakob** [comment]
I'm closing this issue, since Postico now pretty-prints JSONB values automatically in the sidebar, and displays a minimized form in the table view.

The latest build of Postico 2 now additionally allows double clicking a JSON or JSONB cell to open a big popover. This is nice if you don't use the sidebar, or if you want to look at JSON data in the SQL Query view, where we don't yet have a sidebar.

(See https://eggerapps.at/postico2/ for the latest preview of Postico 2)

**Comment by vergenzt** [comment]
Hi - is there any way to configure Postico's JSON pretty printing to apply to [Redshift's JSON column type](https://docs.aws.amazon.com/redshift/latest/dg/r_SUPER_type.html), which confusingly is called "super" instead of "json" or "jsonb"?
