### ISSUE TITLE
The ECDSA host key of the SSH server did not match the fingerprint.

### ISSUE THREAD

**Issue by fuzzmonkey** [jakob/Postico#840]
## What did you do?

Attempted to connect to a database via a bastion box after the bastion box has changed.

![Screenshot 2023-05-02 at 09 05 21](https://user-images.githubusercontent.com/473265/235612747-816a41f0-d13a-4fee-a3e9-f0da9fc62497.png)

## What did you expect to happen?

An option to replace/update the key. IIRC this issue was fixed in v1.x

## What actually happened?

I just see `The ECDSA host key of the SSH server did not match the fingerprint.` 

## What software versions are you using?

Postico version:  2.0.1
macOS version:  13.3.1 (22E261)
PostgreSQL version:  14.7

**Comment by jakob** [comment]
In Postico 2, the fingerprint is shown in the connection settings. Clearing the field should fix the problem.

I don't want to make resetting the fingerprint too convenient, since I want people to stop and think when this happens.

But maybe I should make an exception when the new key is already in the known_hosts file.

**Comment by fuzzmonkey** [comment]
hey @jakob - thanks for the rapid response! That did indeed fix the problem. I hadn't noticed the fingerprint in connection settings.

> But maybe I should make an exception when the new key is already in the known_hosts file.

That would be ideal. Our bastion box gets replaced on most terraform runs, so this happens a lot. At least i know how to fix it going forward!
