### ISSUE TITLE
Feature request: schema-aware autocompletion with LLM

### ISSUE THREAD

**Issue by kyle-villeneuve** [jakob/Postico#842]
It seems like there are some very obvious autocompletions that can be inferred using a language model trained off of the schema of your database, let's say for instance you're writing a query such as 
`SELECT * FROM users JOIN ....` an LLM would know the schema of your users table, see which foreign keys it has and which tables might be referencing it and populate a few autocompletions to join. Or, if you type `JOIN table ` it would already know the foreign key relationship and write the clause for you. There seems to be a lot of low hanging fruit for improved autocompletion, not saying an LLM is the _only_ way to achieve this but I've been very impressed by how good ChatGPT is at writing valid SQL with limited knowledge of your entire database schema. I think something running on the client would be a strict requirement for many, myself included, as I wouldn't want my database schema being sent out to 3rd parties.

**Comment by jakob** [comment]
I've wanted to add these kind of completions for a long time, because I think they are pretty straightforward to implement with basic if/else rules. A similar improvement would be eg. detecting comparisons and assignments to ENUM columns, and automatically suggesting values.

I don't think Postico needs LLM for basic completions like this. Postico already has a parser that should be able to do that with a few minor changes.

The reason why Postico doesn't have completions like this yet is that the auto-complete code is very complicated and I am a bit afraid to touch it, and there have always been more urgent things to work on.

**Comment by kyle-villeneuve** [comment]
I agree 100% an LLM model would be overkill for just autocompleting a join between two tables, my point is that it's just one of many different things an LLM could achieve to improve DX. And I think trying to hand-roll an autocompletion engine would ultimately be more difficult to achieve the same results as even a rudimentary implementation of an LLM.
