### ISSUE TITLE
modifier keys for multicolumn sort

### ISSUE THREAD

**Issue by qwesda** [jakob/Postico#861]
While I like the ability to use multicolumn sorting, it trips me up a lot because it usually is not what I want. 

Maybe it could be invoked by option-clicking a column?

**Comment by qwesda** [comment]
hmmm, if I really want to use multicolumn sort then my mental model would always be highes to lowest order (i.e. the current mode).

Maybe keep the default like this, but add a setting for the sorting behaviour with:

a) multicolumn sort highes to lowest (cmd-click single column sort)
b) multicolumn sort lowest to highes (cmd-click single column sort)
c) single column sort (cmd-click multicolumn sort highes to lowest)

How many people use the dev builds? Have you heard from others about this?

**Comment by qwesda** [comment]
fyi, I very much like the *NULLS first/last* options in the context menu and the *copy column values*

**Comment by jakob** [comment]
> hmmm, if I really want to use multicolumn sort then my mental model would always be highes to lowest order (i.e. the current mode).

Yes, I agree. Maybe a modifier is the better choice.

I don't really want to add a setting for the way the sorting works, because I think this is hard to understand.

> How many people use the dev builds? Have you heard from others about this?

From server logs I estimate that about ~1500 people are using dev build 9666 or newer, but unless something is horribly broken I get very little feedback. And even if something is horribly broken I get very little feedback. I assume that most people don't think their feedback matters. But it does! That's also why Postico has automatic crash reporting. Nobody ever told me when Postico crashed...

Anyway, I think you are the first person to complain about the new sorting behaviour, and I think I agree with you. I'll revert the default to the behaviour it had before, and require a modifier key if you want to multi-sort.

Then I just need to figure out a way to make the feature discoverable. Maybe I can add a hint in the context menu to "hold ⌥ for multisort" or something like this.

**Comment by qwesda** [comment]
1.5K is not nothing, but I also see that filing an issue is a pretty high bar.

Anyways: hint in context menu might be ok even though it will be a bit awkward. Sounds like a really annoying UI problem, that makes me glad that I mostly work on databases!

There are some apps that do have a nice changes/new features screen when new versions are installed. Maybe something like this could work. But it should probably be reserved for important features and be kept relatively small with a link to the changelogs for more details.

**Comment by jakob** [comment]
A second customer complained about the new sort behavior :)

I changed it so that you need to press option to sort by multiple columns. And I added a note to the popup menu. And you can now add sort columns with the "sort priority" submenu.

<img width="442" alt="Bildschirmfoto 2023-12-12 um 15 42 19" src="https://github.com/jakob/Postico/assets/198305/072c93f0-9a57-45ba-acd7-e317ed9435f2">

I'm sure the note in the popup menu goes against all platform conventions, but I really want people to learn about this feature when they need it, and that context menu is where they are most likely to look.

(Maybe I'll add a separate UI for it as suggested in #137, then I can remove the note)
