### ISSUE TITLE
remember window size w/o changing system option

### ISSUE THREAD

**Issue by wellsoliver** [jakob/Postico#98]
Mentioned this on Twitter, but I would love it if Postico remembered its window size-- I change it every time I run it.

I have 'Close windows when quitting an app' checked in system preferences and to keep it that way as I hate a bunch of windows remaining open, but would like default window size remembered.

**Comment by wellsoliver** [comment]
Just annoyingly asking about this again. Any chance postico could remember its last width and just resume it? Or a setting in Preferences? <3

**Comment by jakob** [comment]
Hi @wellsoliver 

Thanks for your reminder!

It turns out that Interface builder has a checkbox for autosaving window size --> so implementing this feature turned out to be trivial.

You can download the latest build here:
https://eggerapps-downloads.s3-eu-west-1.amazonaws.com/postico-1334.zip

Let me know if this works for you!

**Comment by wellsoliver** [comment]
<3 x100

**Comment by wellsoliver** [comment]
When do you plan to do a full proper release w/ this and the font sizes, etc?

**Comment by jakob** [comment]
This week, if no further bugs with it come up.

**Comment by jakob** [comment]
I've until this week until the new version of libssh2 was released. You can now download the final version here: https://eggerapps.at/postico/

(unless you have the MAS version, which will still take a few days)
